### ISSUE TITLE
Screenshot quality degradation affects visual analysis accuracy

### ISSUE THREAD

**Issue by libertyteeth** [cline/cline#1003]
### What happened?

When capturing screenshots during browser sessions, Cline is using WebP format with default compression settings, which introduces quality loss. This affects the accuracy of visual analysis in two ways:

1. False Positives: Compression artifacts are misinterpreted as visual defects, causing Cline to report errors in elements that are actually correct.

2. False Negatives: Real visual defects are masked by compression artifacts, causing Cline to miss actual issues that should be detected.

The issue is particularly noticeable with:
- Fine text (< 12px)
- Sharp edges and 1px lines
- Gradient transitions
- Color accuracy checks

### Steps to reproduce

1. Create a test page with precise visual elements:
```html
<!DOCTYPE html>
<html>
<head>
    <style>
        .thin-line { width: 100px; height: 1px; background: #000; }
        .gradient { height: 50px; background: linear-gradient(to right, #fff, #000); }
        .fine-text { font-size: 8px; }
    </style>
</head>
<body>
    <div class="thin-line"></div>
    <div class="gradient"></div>
    <div class="fine-text">Small text for quality testing</div>
</body>
</html>
```

2. Run Cline analysis:
```typescript
const result = await cline.analyzeVisual('test.html');
console.log(result.issues);
```

3. Compare with direct browser screenshot:
   - Open test.html in Chrome
   - Take screenshot manually
   - Notice quality difference in:
     * 1px line (appears blurry in Cline)
     * Gradient (shows banding in Cline)
     * Small text (less readable in Cline)

### Relevant API REQUEST output

```shell
// Current implementation in BrowserSession.ts
let screenshotBase64 = await this.page.screenshot({
    ...options,
    type: "webp", // Uses lossy compression by default
});

// Console output shows compression artifacts:
[Error] Visual analysis failed:
- Element <div class="thin-line"> appears blurred (actual: sharp)
- Gradient shows banding artifacts
- Text element <div class="fine-text"> fails clarity check
```

### Additional context

- Issue affects all screenshot captures
- Reproducible across different browsers and platforms
- Impact increases with:
  * More complex visual elements
  * Finer details in UI
  * Color-sensitive components
  * Text-heavy interfaces

**Environment:**
- Cline Version: 3.0.4
- Puppeteer Version: ^23.4.0
- Node.js Version: 18.x
- OS: Arch Linux

**Proposed Solution:**
Use PNG as primary format for lossless quality, with high-quality WebP as fallback only when needed. This ensures:
- No compression artifacts
- Accurate visual analysis
- Reliable test results
![Screenshot from 2024-12-22 14-40-11](https://github.com/user-attachments/assets/384c16ac-b785-4ca5-9964-04a67932f2bc)
![Cline hallucinates what he sees in the browser, then when I give him the image he sees clearly  Guessing there's image compression happening in his browser - Screenshot from 2024-12-22 14-42-52](https://github.com/user-attachments/assets/a0712706-2e46-4356-b99a-152f59e2e835)

--

FYI, this is my first contribution to this project.  I asked Cline to help write this, after reviewing only CONTRIBUTING.md.  Then I asked Cline to review CODE_OF_CONDUCT.md, and zero changes were required: Cline writes positively by default.  Thank you so much for this wonderful creation.

**Comment by libertyteeth** [comment]
On reviewing after posting, I see an error.  The version Cline wrote [guessed at, I suppose?] is incorrect: I am running version 3.0.4.

A fix is forthcoming.

**Comment by saoudrizwan** [comment]
Closing per https://github.com/cline/cline/pull/1011#issuecomment-2561600219

**Comment by saoudrizwan** [comment]
> Thank you so much for this wonderful creation.

Thank you for taking the time to investigate and contribute @libertyteeth. I'm sorry I couldn't merge it in the end, but please don't let that stop you from taking a stab at another itch. I ended up learning way more about webp thanks to your issue/PR and it's interesting how much of a difference a slight bump in quality can have in file size.

**Comment by libertyteeth** [comment]
> > Thank you so much for this wonderful creation.
> 
> Thank you for taking the time to investigate and contribute @libertyteeth. I'm sorry I couldn't merge it in the end, but please don't let that stop you from taking a stab at another itch. I ended up learning way more about webp thanks to your issue/PR and it's interesting how much of a difference a slight bump in quality can have in file size.

Thank you for your kind response.  I was gut punched by a non-blood family relative last night and left the celebration and haven't returned.  This affected my response, which was after I had gotten home.

What do you think of a configuration option?  I am happy to work on it if it will meet your approval.

Thank you again, and Merry Christmas.
