### ISSUE TITLE
When using run command, cline doesn't configure the shell correctly using `.zshrc`

### ISSUE THREAD

**Issue by apoorvagnihotri** [cline/cline#1008]
### What happened?

What cline suggested and I approved
![image](https://github.com/user-attachments/assets/e4293af3-3535-4faf-9798-4da983e000d8)

My `.zshrc`
![image](https://github.com/user-attachments/assets/9f2ac52e-62db-4af2-a6be-edade2583bb7)

When creating a new shell manually, I can access npm via the shell. I am not sure why cline can't access it.
![image](https://github.com/user-attachments/assets/00a745c2-378a-4bb5-8e24-22325c4c1d0b)

I tried reproducing the way cline creates a shell, but I am able to access npm still
![image](https://github.com/user-attachments/assets/621cdcaa-ff08-46f9-b439-02f22d405eaf)

### Steps to reproduce

1. Install node using nvm
2. Use cline to run some command with `npm` or `node`.
3. The shell that cline creates doesn't have the required path to the commands.

### Additional context

I have powerlevel10k installed.

**Comment by apoorvagnihotri** [comment]
I solved it for now using the following `.zshrc`.

![image](https://github.com/user-attachments/assets/164f5689-4805-40b1-89d9-6cf26ea9c1e8)

**Comment by saoudrizwan** [comment]
Thank you for digging into this and finding a workaround. Issues with vscode's shell integration are not uncommon–I suggest trying to create a minimally reproducible environment for the bug using https://github.com/saoudrizwan/shell-integration-problems and opening an issue there so we can forward it to the vscode team.
