### ISSUE TITLE
Why can't I use search or use the browser? It's stuck here all the time

### ISSUE THREAD

**Issue by ottopan** [cline/cline#1034]
### What happened?

I allowed the use of the browser, but it has never responded
![1](https://github.com/user-attachments/assets/c59e5827-3fce-4694-8891-a778621bcede)

### Steps to reproduce

like “what happened”

### Operating System

macos Ventura 13.0.1

### Cline Version

lastest

**Comment by saoudrizwan** [comment]
It could be that this URL is blocked for you? You can hit the cancel button and tell Cline to do something else.

**Comment by ottopan** [comment]
Impossible to be blocked, my browser can access Google normally

**Comment by ottopan** [comment]
> It could be that this URL is blocked for you? You can hit the cancel button and tell Cline to do something else.

Is it possible that the proxy issue is with the plugin itself? I'm using it on Cursor, and Cursor's own execution of Google searches works perfectly fine.

**Comment by entrepeneur4lyf** [comment]
MCP Playwright works in the meantime just fyi

**Comment by bluegenester** [comment]
came across similar issue, it proceeded correctly after updating the permissions, please check if this it matches. 

<img width="535" height="185" alt="Image" src="https://github.com/user-attachments/assets/928ae867-4a93-426e-a4a6-92ad38c931c6" />
