### ISSUE TITLE
running task stopped cline moving on

### ISSUE THREAD

**Issue by donghao1393** [cline/cline#1064]
### What happened?

when cline want to start server, like `cargo run` or `npm run dev`, it would stop there while command running in the terminal.
expected: cline should move on once read listening/starting text on the terminal.

### Steps to reproduce

1. get a project
2. ask cline to do something by starting the server
3. it would hang there with `proceed while running `

### Operating System

macOS Sonoma

### Cline Version

3

**Comment by julesmons** [comment]
The "proceed while running" button is clickable.

**Comment by donghao1393** [comment]
> The "proceed while running" button is clickable. :)

Oh, I will check
