### ISSUE TITLE
The Cline does not work with local ollama model.

### ISSUE THREAD

**Issue by normanify** [cline/cline#1068]
### What happened?

1. The settings are just like this:
<img width="660" alt="image" src="https://github.com/user-attachments/assets/af611252-eb2b-4eb2-9320-dd79c988deb8" />

2. I sent a message 'write a classic brick shooting game using python.' in the Cline input box, but got this error message:
<img width="635" alt="image" src="https://github.com/user-attachments/assets/ece8b492-4b6b-49bd-9f78-2d8e1af420c1" />

the final error messages are:

`execute_mcp_command mkdir todo-app

Cline is having trouble...
Cline uses complex prompts and iterative task execution that may be challenging for less capable models. For best results, it's recommended to use Claude 3.5 Sonnet for its advanced agentic coding capabilities`

### Steps to reproduce

1. Set a local network IP as Ollama BaseURL.
2. Select any model available.
3. Send command in Cline but get error messages.

### Operating System

Ollama: Ubuntu 24.04, Cline: macos m1 Sequoia 15.2

### Cline Version

3.0.9

**Comment by saoudrizwan** [comment]
The extension doesn't work too well with local models, but people have had good results running qwen on a beefy macbook. I also suggest giving deepseek v3 on OpenRouter a try to get nearly free inference with just as good results as claude sonnet.

**Comment by grapeot** [comment]
@normanify I got the same issue and think I've figured out a way to resolve this. It's probably because the default context window of Ollama is too short (4096 I think). You need to manually configure the model to accept longer context. I tried it and seemed to get the problem solved. My guess is the prompt is longer than 4096 tokens and in the beginning of the prompt it mentioned a React based to do app. The real request would appear later but didn't make it to the context window.

**Comment by dev-bhaskar8** [comment]
> [@normanify](https://github.com/normanify) I got the same issue and think I've figured out a way to resolve this. It's probably because the default context window of Ollama is too short (4096 I think). You need to manually configure the model to accept longer context. I tried it and seemed to get the problem solved. My guess is the prompt is longer than 4096 tokens and in the beginning of the prompt it mentioned a React based to do app. The real request would appear later but didn't make it to the context window.

can you tell me how you changed it? Also the model cannot use tool use.

**Comment by grapeot** [comment]
> > [@normanify](https://github.com/normanify) I got the same issue and think I've figured out a way to resolve this. It's probably because the default context window of Ollama is too short (4096 I think). You need to manually configure the model to accept longer context. I tried it and seemed to get the problem solved. My guess is the prompt is longer than 4096 tokens and in the beginning of the prompt it mentioned a React based to do app. The real request would appear later but didn't make it to the context window.
> 
> can you tell me how you changed it? Also the model cannot use tool use.

https://github.com/ollama/ollama/issues/3643 Here is an example. 

I didn't really get the problem of not being able to use tools. Actually, if the LLM doesn't invoke any tools, this will trigger an error in the client, and it will tell the LLM to restart.

**Comment by dev-bhaskar8** [comment]
If I use openrouter, same model, does tool use, open files edit etc. Local llm just prints the actions and nothing happens. The same exact model, I even used open ai compatible end point. But local llm just doesn't edit files etc.

**Comment by dev-bhaskar8** [comment]
It does say error, no tool use, try again but nothing happens

**Comment by grapeot** [comment]
> If I use openrouter, same model, does tool use, open files edit etc. Local llm just prints the actions and nothing happens. The same exact model, I even used open ai compatible end point. But local llm just doesn't edit files etc.

I see. I guess this might mean the LLM itself doesn't support tool use. What LLM are you using? I used QWen2.5-coder-32k and it seems to work well.

**Comment by TomWangTomWang** [comment]
1,Export the configuration
ollama show --modelfile "deepseek-r1:14b" > deepseek-r1-14b-32k.Modelfile
2,Open deepseek-r1-14b-32k.Modelfile using Notepad.
3,Manually modify the content
# Original content:
FROM ollama/llama2:latest  # or other default content
# Modify to:
FROM deepseek-r1:14b
4,Manually add parameters
Append the following line to the end of the file:
PARAMETER num_ctx 32768
5,Create a new model
ollama create deepseek-r1-14b-32k -f deepseek-r1-14b-32k.Modelfile
6,Verify the operation
# Check the list of installed models
ollama list

Try above method,it works.

**Comment by qbyss** [comment]
> > > [@normanify](https://github.com/normanify) I got the same issue and think I've figured out a way to resolve this. It's probably because the default context window of Ollama is too short (4096 I think). You need to manually configure the model to accept longer context. I tried it and seemed to get the problem solved. My guess is the prompt is longer than 4096 tokens and in the beginning of the prompt it mentioned a React based to do app. The real request would appear later but didn't make it to the context window.
> > 
> > 
> > can you tell me how you changed it? Also the model cannot use tool use.
> 
> [ollama/ollama#3643](https://github.com/ollama/ollama/issues/3643) Here is an example.
> 
> I didn't really get the problem of not being able to use tools. Actually, if the LLM doesn't invoke any tools, this will trigger an error in the Cline, and it will tell the LLM to restart.

Can you be more explicit on how you did it ? the thread you linked is confusing. Where am I suppose to put that /set parameter ? Especially on windows.

**Comment by minyor** [comment]
> > > > [@normanify](https://github.com/normanify) I got the same issue and think I've figured out a way to resolve this. It's probably because the default context window of Ollama is too short (4096 I think). You need to manually configure the model to accept longer context. I tried it and seemed to get the problem solved. My guess is the prompt is longer than 4096 tokens and in the beginning of the prompt it mentioned a React based to do app. The real request would appear later but didn't make it to the context window.
> > > 
> > > 
> > > can you tell me how you changed it? Also the model cannot use tool use.
> > 
> > 
> > [ollama/ollama#3643](https://github.com/ollama/ollama/issues/3643) Here is an example.
> > I didn't really get the problem of not being able to use tools. Actually, if the LLM doesn't invoke any tools, this will trigger an error in the Cline, and it will tell the LLM to restart.
> 
> Can you be more explicit on how you did it ? the thread you linked is confusing. Where am I suppose to put that /set parameter ? Especially on windows.

You need to run the model from terminal like so:
ollama run qwen2.5-coder-extra-ctx:14b

Then when you get >>> symbols at the new line, paste:
/set parameter num_ctx 32768

And hit Enter.
Except it dosn't help at all, for me at least, no matter what model I try and what context size I set, the models are not follow cline's rules :(

I read somewhere that cline works perfectly with LM Studio but not with Ollama on same models.
Can it be a regression, maybe downgrading Ollama itself is an option?

**Comment by tzelalouzeir** [comment]
im getting API error and i have already the git and everything even i change the num_ctx to 32k but still same errors...

![Image](https://github.com/user-attachments/assets/879342dc-1e5a-43ce-84d6-5a2c8cbab4f9)

![Image](https://github.com/user-attachments/assets/bbc5d7dc-9c15-4316-b22b-c4b069719d1f)

**Comment by codejq** [comment]
@tzelalouzeir 

You need to remove the last slash 
instead of 
http://localhost:11434/
use 
http://localhost:11434

**Comment by minyor** [comment]
> im getting API error and i have already the git and everything even i change the num_ctx to 32k but still same errors...
> 
> ![Image](https://github.com/user-attachments/assets/879342dc-1e5a-43ce-84d6-5a2c8cbab4f9)
> 
> ![Image](https://github.com/user-attachments/assets/bbc5d7dc-9c15-4316-b22b-c4b069719d1f)

Alternativelly you can select OpenAI Compatible instead of Ollama and use this url:
http://localhost:11434/v1

**Comment by codejq** [comment]
On your configuration you need to remove the slash from the server name
That the reason you are getting 404 error

**Comment by scoropeza** [comment]
> 1,Export the configuration ollama show --modelfile "deepseek-r1:14b" > deepseek-r1-14b-32k.Modelfile 2,Open deepseek-r1-14b-32k.Modelfile using Notepad. 3,Manually modify the content
> 
> # Original content:
> FROM ollama/llama2:latest # or other default content
> 
> # Modify to:
> FROM deepseek-r1:14b 4,Manually add parameters Append the following line to the end of the file: PARAMETER num_ctx 32768 5,Create a new model ollama create deepseek-r1-14b-32k -f deepseek-r1-14b-32k.Modelfile 6,Verify the operation
> 
> # Check the list of installed models
> ollama list
> 
> Try above method,it works.

This worked for me as well, although I noticed that some models have problems when trying to use the "plan" mode of cline, as they seem to be unaware about how to use the expected tools that are part of it.

**Comment by minyor** [comment]
Here is the most easy way:
For example model "deepseek-coder-v2:16b" and context size 16kb

ollama run deepseek-coder-v2:16b
>>> /set parameter num_ctx 16384
>>> /save deepseek-coder-v2:16b
Ctrl+D

**Comment by ahmadkalantari** [comment]
DONT USE OLLAMA! USE LMSTUDIO !!! 🙌
