### ISSUE TITLE
While working on adding Dart support I am not able to successfully integrate tree-sitter-dart.wasm in claude-dev

### ISSUE THREAD

**Issue by go-run-jump** [cline/cline#134]
## Description

I'm working on adding support for Dart in claude-dev using the `tree-sitter-dart` package (https://www.npmjs.com/package/tree-sitter-dart). However, I'm encountering issues with incorporating the WASM file into the build process, and subsequently having the dart support in claude-dev.

## Current Behavior

The WASM file is not being loaded correctly in `languageParser.ts`. What I notice there is that the loading mechanism doesn't seem to be using the the location where the WASM files are supposed to be copied according to `esbuild.js`.

## What I want to achieve

The WASM file should be properly incorporated into the build and loaded correctly by `loadLanguage` in  `languageParser.ts`.

## Questions

1. Is there any special consideration or step I'm missing when adding the WASM file to the build?
2. How should the WASM file be correctly referenced in `languageParser.ts`?
3. Are there any specific configurations needed in `esbuild.js` to ensure the WASM file is copied to the correct location?

## Additional Context

- I'm using `tree-sitter-dart` version: 1.0.0
- Claude-dev version/commit: f9b517c4d0895efc6f9204c48437a77c76d54d5f

Any guidance would be greatly appreciated.

**Comment by JustTryAI** [comment]
@go-run-jump Dart support been included directly into tree-sitter, https://github.com/tree-sitter/tree-sitter/wiki/List-of-parsers, so no need for tree-sitter-dart.
