### ISSUE TITLE
Feature request: Custom instructions prompt in the project (.context.md)

### ISSUE THREAD

**Issue by ghodss** [cline/cline#136]
Claude Dev is especially powerful when augmented with extensive custom instructions that inform the AI about the design of the project, API's of significant libraries or services in use, the architecture of the application, and so on. But currently custom instructions can only be modified manually inside the GUI. By implementing an option to have Claude Dev source custom instructions from a file inside my project, I can both:

* Use version control to version and share my custom instructions, improving the quality and consistency of the generations across my entire team.
* Create commands to easily manage and generate custom instructions depending on which part of the codebase I'm working on to focus the AI's attention.

**Comment by saoudrizwan** [comment]
This is a great suggestion! Something along the lines of a `.claude-prompt` at the root of your project, where at the beginning of each task this file is always appended to the system prompt?

**Comment by georgesimbe** [comment]
I definitely agree with this suggestion. I've been testing out custom instructions and I've seen improvements in design consistency and overall output quality.

Custom instructions from a file in the project is could be good for team collaboration, and focused assistance prompting, particular when you specific to focus on one aspect or a page, ClaudeDev does well at this

**Comment by ghodss** [comment]
Yes exactly. The exact file path could even be specified in the settings UI through a dropdown that allows the user to choose between the existing text box or a project file path. The default though should probably be .claude-dev-prompt to properly namespace the file to this specific extension.

**Comment by looeee** [comment]
It seems like system_prompt.txt in the project root is becoming an informal standard so maybe the extension can read that file?

**Comment by gfsysa** [comment]
as a workaround we've been adding "Begin by reviewing instructions.md" in the custom instructions, so far so good

**Comment by keypuncherlabs** [comment]
I've been keeping all my instructions in a markdown for the time being and copying it in each time, I was looking for something just like this!

**Comment by ItsReddi** [comment]
Good idea, i would suggest to make the name of the file configurable, defaulting to `.claude-prompt`

**Comment by Madd0g** [comment]
I was thinking of submitting this feature request, in my mind - there could be a file per folder and not just in the root. To be able to explain some big and complex sub-feature verbosely, but not include it in the context for unrelated tasks.

**Comment by looeee** [comment]
>  there could be a file per folder and not just in the root

At that point, a RAG over the codebase would be the best solution. I'm not sure it would fit in the scope of this project, however.  I've been thinking about this recently and the solution I've come up with is a small LLM that would read and improve your prompts using RAG before sending them to the large (expensive) agentic LLM.

So your initial prompt might looks like:

> Take a look at `/components/ListA.tsx`.  Please ensure that the the list generated by this component follows accessibility best practices.

Then a basic version of the *prompt improver* might output a prompt like this:

> Take a look at `/components/products/ProductList.tsx`.  Please ensure that the the list generated by this component follows accessibility best practices.
> The `ProductList` component uses `/components/lists/ItemList.tsx` and `/components/lists/ItemDetail.tsx`. `ItemList` and `ItemDetail` are also used in `/components/cart/ShoppingCard.tsx` and `/components/orders/RecentOrder.tsx`. Please ensure that all files continue to work following any changes that you make.

**Comment by themightychris** [comment]
You can achieve this now by adding to your global custom instructions something like:

```
- Before starting each task, check if a `.claude-prompt` file exists and if it does, review it for important project-specific instructions and guidance
```

**Comment by saoudrizwan** [comment]
Added `.clinerules` in v3!
