### ISSUE TITLE
Weird issue with file edits

### ISSUE THREAD

**Issue by maxiedaniels** [cline/cline#161]
When ClaudeDev edits a file, i see the diff show up first, and then i hit approve. It does some processing in the background, then the file just suddenly goes back to how it was. The weird part is that after trying it three times and the new edits kept disappearing, I decided to just copy paste the edits into the file and hit save. Then I got an error saying the file has been changed since - and when i hit compare, it showed the file *does* have the new edits, but seemingly VScode didn't refresh the file. Why would this happen? VSCode always updated files changed outside of the IDE so i figure this must be a ClaudeDev issue.

**Comment by paj80paj** [comment]
I've been getting this

**Comment by saoudrizwan** [comment]
The extension writes directly to the file so I have to imagine this is bc vscode gets into a weird state where the open editor version and the version on disk are out of sync. Please try restarting vscode and let me know if you're still consistently running into this.
