### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by radonn24** [cline/cline#3]
I was working on the task and must have asked Claude to perform too many things in a short amount of time, or made a large request and hit a rate limit.

```
API request failed:
429 {"type":"error","error":{"type":"rate_limit_error","message":"Number of request tokens has exceeded your per-minute rate limit (https://docs.anthropic.com/en/api/rate-limits); see the response headers for current usage. Please reduce the prompt length or the maximum tokens requested, or try again later. You may also contact sales at https://www.anthropic.com/contact-sales to discuss your options for a rate limit increase."}}
```

This stopped Claude Dev from working, and I could not stop the current action, or break out of the error message. In order to break out of this, I simply clicked the "+" button to start a new chat. Now there is no way to enter back into the previous chat thread, or pick up where I left off.

Thoughts on this? Am I doing anything wrong, or missing something obvious (for resuming a chat thread)? (I have now read the docs discussing rate limits, so I understand that part now).

Any help is much appreciated! Very slick tool so far!! 😎

**Comment by saoudrizwan** [comment]
Kind of a late reply... my apologies. But you should use OpenRouter! They now support prompt caching and have better rate limits
