### ISSUE TITLE
Bug: Endless unnecessary edits due to inaccurate auto-generated screenshots

### ISSUE THREAD

**Issue by techcow2** [cline/cline#394]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

It provides itself with a screenshot that is missing content, when that isn't actually true. This sends it into an endless mission to fix the issue.

### Steps to reproduce

1. Ask it to build a landing page
2. Allow it to build and wait for it to provide itself with a screenshot 
3. Notice the missing content and how it tries to fix it endlessly because the screenshots aren't capturing the detail

### Additional context

![Screenshot 2024-09-25 080534](https://github.com/user-attachments/assets/317ad754-f96f-4278-9730-9ae5a8d756ac)

**Comment by devprimed** [comment]
Context/feature disablement options are needed here, it will frequently run down a typescript error rabbit-hole, burning tokens with constant re-writes.

**Comment by techcow2** [comment]
no longer a problem
