### ISSUE TITLE
o1-mini/o1-preview not working in v2.0

### ISSUE THREAD

**Issue by chun1617** [cline/cline#445]
### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

o1-preview

### What happened?

OpenAI doesn't support stream in o1 model yet, so could you please add an option to enable or disable stream

### Steps to reproduce

1. setup openAI Compatible
2. using o1-preview
3. got error

**Comment by SatoshiReport** [comment]
+1

**Comment by Luis-Munu** [comment]
Having the same issue here, just selected OpenAI as provider, added the key and o1-mini as the model. As soon as a prompt is sent, it returns API request failed.

400 Unsupported value: 'messages[0].role' does not support 'system' with this model.

**Comment by tttollerer** [comment]
I have same Issue with all OpenAI Models. How can i change "system" to "user" for example?

**Comment by MrDedalus** [comment]
Im having the same issue since the Cline update.I am getting the  same error message when I select 01 preview or preview mini - https://github.com/cline/cline/issues/434. This is the best AI coder, far superior to Cursor imho

**Comment by saoudrizwan** [comment]
Fix in v2.0.8, thanks for the patience!

**Comment by araimbekoff** [comment]
> Fix in v2.0.8, thanks for the patience!

no, not yet working
![image](https://github.com/user-attachments/assets/753e24d6-7a56-465d-9722-5e352e0e74ab)

**Comment by tmoulderinx** [comment]
Cline version:  v2.0.16
API Provider: OpenAI Compatible
model ID:  o1-mini
![image](https://github.com/user-attachments/assets/675a3429-bf72-44f4-8753-471b9af1219b)

Same for o1-preview

**Comment by hardikcc** [comment]
any update on this?

**Comment by elmathzen** [comment]
I had the same issue and I just remove streaming from the setting and it works for o1-mini and o3-mini, for the moment this model is not supporting streaming

**Comment by araimbekoff** [comment]
> > I had the same issue and I just remove streaming from the setting and it works for o1-mini and o3-mini, for the moment this model is not supporting streaming
> 
> I could not find how to disable streaming in the latest version. (Using OpenAI Compatible provider). Would you have any hint please? I checked the Model configuration and the extension settings but I must have missed something. Trying to use o1-mini but I'm also getting the 400 unsupported system issue. Thanks :)

Download the plugin source code.
Find the code that initializes o1-mini in OpenAI.
Replace the OpenAI client with AzureOpenAI.
Insert baseUrl, apiKey, and model from your credentials.
Compile it and enjoy!
P.S. In this case, just select OpenAI and the o1-mini model. Instead of the key, enter anything.
