### ISSUE TITLE
How to turn off streaming?

### ISSUE THREAD

**Issue by As-Tomas** [cline/cline#491]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Sonet

### What happened?

This new streaming function is useless, the user unable to do other tasks while stream in progress, plus adds multiple undo steps. If not possible to turn off then what last version is without it?

### Steps to reproduce

1. Jut
2. Try 
3.To use

**Comment by As-Tomas** [comment]
Solution: got to Extensions->Cline-> right click -> Install Specific Version -> 1.9.7

**Comment by tle211212** [comment]
There should be an option to disable this feature. My project contains a few large source files. Seeing the streaming thing makes me feel that it is slower than 1.9.7 (without streaming).

**Comment by As-Tomas** [comment]
There should be an option to disable this feature

**Comment by jeanlucmongrain** [comment]
that is just terrible, vscode is unsuable when cline is performing file changes, I can't work on other files, because the keyboard focus can switch anytime back to the diff/update stream

**Comment by gaby** [comment]
@As-Tomas Please re-open this. This is still an issue with every model.

**Comment by crimeofheart** [comment]
Please implement streaming switch so that for models which do not support streaming Cline is usable again.
