### ISSUE TITLE
Cline not sending the task to locally hosted Ollama 

### ISSUE THREAD

**Issue by startmd** [cline/cline#511]
### Which API Provider are you using?

Ollama

### Which Model are you using?

Llama 3.2: 8b

### What happened?

I am using the default url with Ollama and Llama 3.2: 8B to generate some basic CRUD files in PHP. My prompt is "You are a PHP Expert here to write code and build necessary files and folders to complete my project"

For some reason, whenever Cline sends a request, the reply mentions that it has understood the environment and context (which it does guess correctly to be Laravel) but mentions that user has not given any specific task and aska for the same.
Cline for reason sends the same API request again till it hangs 

### Steps to reproduce

1. Use any model with Ollama
2. With Cline 2.0.5, try to give a simple prompt 
3. The issue didn't exist for ClaudeDev 1.9.7

**Comment by prod2zzr** [comment]
same problem bothers me for two days : (

**Comment by MohammedInTheCloud** [comment]
same problem

**Comment by wuqqers** [comment]
I have the same problem, did you find a solution?

**Comment by zachmcd09** [comment]
Same issue here regardless of model.

**Comment by wuqqers** [comment]
> ### Which API Provider are you using?
> 
> Ollama
> ### Which Model are you using?
> 
> Llama 3.2: 8b
> ### What happened?
> 
> I am using the default url with Ollama and Llama 3.2: 8B to generate some basic CRUD files in PHP. My prompt is "You are a PHP Expert here to write code and build necessary files and folders to complete my project"
> 
> For some reason, whenever Cline sends a request, the reply mentions that it has understood the environment and context (which it does guess correctly to be Laravel) but mentions that user has not given any specific task and aska for the same. Cline for reason sends the same API request again till it hangs
> ### Steps to reproduce
> 
>     1. Use any model with Ollama
> 
>     2. With Cline 2.0.5, try to give a simple prompt
> 
>     3. The issue didn't exist for ClaudeDev 1.9.7
> 
> 
> ### Relevant API REQUEST output
> 
> _No response_
> ### Additional context
> 
> _No response_
![sil](https://github.com/user-attachments/assets/99c1fbe1-b8a7-4f95-b843-eaaa63343d85)

Hey everyone, I found a temporary solution! You'll need LM Studio to make this work. First, install and launch LM. Then, find and download the model you want to use from within LM. After that, start the server from the left-hand tab, and copy the API details from the right-hand side. In VSCode, open the Cline extension, choose the option to ollama and go back the LM take it server url and model api identifier then paste the URL and the 'This model's API identifier' into the Model ID field. You’re all set!
Note: If you encounter any errors, go to the 'Load' tab in LM Studio and increase the 'Content text' value

**Comment by wuqqers** [comment]
Hey everyone @zachmcd09 @DEAD1SIDE  @MohammedInTheCloud  @prod2zzr  @startmd, I found a temporary solution! You'll need LM Studio to make this work. First, install and launch LM. Then, find and download the model you want to use from within LM. After that, start the server from the left-hand tab, and copy the API details from the right-hand side. In VSCode, open the Cline extension, choose the option to ollama and go back the LM take it server url and model api identifier then paste the URL and the 'This model's API identifier' into the Model ID field. You’re all set!
Note: If you encounter any errors, go to the 'Load' tab in LM Studio and increase the 'Content text' value
![sil](https://github.com/user-attachments/assets/050e1365-df1e-4667-8633-b5668f82998e)

**Comment by bartwisch** [comment]
thanks! i installed the same model and when i try to create a snake clone i get the endles loop with the error "I apologize for that oversight. Let's retry with a tool use.

The user wants to create a Snake clone. We have created the project directory and initialized a new Node.js project. Now, we need to set up the basic file structure and implement the game logic."

do you have any idea?

**Comment by zachmcd09** [comment]
Thank you @wuqqers , this was a decent workaround. models work surprising well, qwen 2.5 coder was hit or miss, codestral was better.
NOTE: Initial prompt uses ~5000 tokens, so set context window accordingly (at least 16384).
Testing with Mistral large to see how it compares.. Should be better, slower but better.

**Comment by wuqqers** [comment]
> Teşekkür ederim @wuqqers , bu iyi bir geçici çözümdü. modeller şaşırtıcı derecede iyi çalışıyor, qwen 2.5 kodlayıcı vuruldu veya kaçırıldı, codetral daha iyiydi. NOT: İlk istem ~5000 belirteç kullanır, bu nedenle bağlam penceresini buna göre ayarlayın (en az 16384). Nasıl karşılaştırıldığını görmek için Mistral Large ile test yapıyoruz.. Daha iyi, daha yavaş ama daha iyi olmalı.

Ahahaa all the time bro, developers are there to help each other! have a happy day!

**Comment by urbandroid** [comment]
I have tried bunch of models and none of them works it has nothing to do with models people Cline is broken

**Comment by mbetrifork** [comment]
I can confirm this issue is happening here as well. Tried with starcoder, gemma and llama 3.2. I get different errors but they all seem to indicate that Cline is not sending over the task prompt correctly.

**Comment by faalbane** [comment]
Any update(s) here? Seeing same thing.

**Comment by wwjCMP** [comment]
+1

**Comment by mjtechguy** [comment]
+1

**Comment by rubaot** [comment]
If you increase the model context size in ollama it will work again. To increase the size create an custommodel file, after that apply it to the model.

Example contents for Modelfile:

```
# Modelfile
FROM qwen2.5-coder:7b
PARAMETER num_ctx 32768
```

This example will increase it to 32K (choose lower for less VRAM). Apply it to a model using command:

ollama create -f Modelfile qwen2.5-coder:7b

**Comment by MohammedInTheCloud** [comment]
**The issue is now resolved, thanks to [@rubaot](https://github.com/rubaot)! Thanks!**

**Comment by damarges** [comment]
> If you increase the model context size in ollama it will work again. To increase the size create an custommodel file, after that apply it to the model.
> 
> Example contents for Modelfile:
> 
> ```
> # Modelfile
> FROM qwen2.5-coder:7b
> PARAMETER num_ctx 32768
> ```
> 
> This example will increase it to 32K (choose lower for less VRAM). Apply it to a model using command:
> 
> ollama create -f Modelfile qwen2.5-coder:7b

But qwen2.5-coder is not supposed to work with Cline, is it? I thought we especially need the qwen2.5-coder-tools for that?

**Comment by MohammedInTheCloud** [comment]
I'm using it now, and it works just fine. [damarges](https://github.com/damarges)

**Comment by eakkawat** [comment]
@damarges  I use this one and It works. 
https://ollama.com/hhao/qwen2.5-coder-tools

**Comment by damarges** [comment]
> @damarges I use this one and It works. https://ollama.com/hhao/qwen2.5-coder-tools

do you extend the context window or just use it as it is ?

**Comment by eakkawat** [comment]
> > @damarges I use this one and It works. https://ollama.com/hhao/qwen2.5-coder-tools
> 
> do you extend the context window or just use it as it is ?

Use it as it is.

**Comment by SavageRambo** [comment]
just increase models context value
ive tested llama3.2 and qwen2.5-coder,both works fine for me.llama3.2 eg:
1.enter llama3.2 in CLI
```
ollama run llama3.2 
```
2.edit modelfile and set the default context value to a higher one,make sure you were active the model,command typing after >>>
```
/set para meter num_ctx 8192 
```
higher context value costs more VRAM or RAM,based on twice of the model size and the context part.
3.save setting
```
/save llama3.2 
```
finally,reload llama3.2 in cline,it should work.

**Comment by dominsights** [comment]
What fixed my issue was closing and re-opening vscode. My context is already at 32k.
