### ISSUE TITLE
Weird Php issue

### ISSUE THREAD

**Issue by alfi4000** [cline/cline#513]
### Which API Provider are you using?

Google Gemini

### Which Model are you using?

Gemini Dev Api

### What happened?

It keeps Removing <> and changes it to the weird thing in the screenshot!
<img width="1246" alt="Screenshot 2024-10-12 at 10 33 41" src="https://github.com/user-attachments/assets/e6a64500-5b39-494e-be1c-5502be8da6ac">

### Steps to reproduce

1. Just use a php code and let it do modifications!
2.
3.

**Comment by saoudrizwan** [comment]
Fixed in v2.0.6

**Comment by alfi4000** [comment]
ok
