### ISSUE TITLE
Error writing file: Failed to open diff editor

### ISSUE THREAD

**Issue by youngrichu** [cline/cline#525]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

gemini-1.5-flash-002

### What happened?

![image](https://github.com/user-attachments/assets/a682fcb8-a26a-429e-a8b5-991b5f0f921a)

I keep getting this error and i don't have any other extension. I'm running it on google idx

### Steps to reproduce

1.
2.
3.

**Comment by saoudrizwan** [comment]
It seems like project idx is very slow to open the diff editor, I adjusted the timeout waiting for it to open so it should fix this issue. Please lmk if v2.0.8 helps with this

**Comment by MrMophandle** [comment]
Still seeing the messages, running 2.0.8.  OpenRouter, using Sonnet 3.5

![Screenshot 2024-10-16 at 9 32 54 PM](https://github.com/user-attachments/assets/c366dc1b-5c13-464b-8098-a5567be296fe)

**Comment by AlexanderHel** [comment]
Same problem with 2.0.9, Vertex AI sonnet 3.5
![image](https://github.com/user-attachments/assets/1c6abe32-7925-4812-bcb0-ea55e57341f3)

**Comment by hangingman** [comment]
Same here, the problem might be related with VSCode extention, not cline itself.

**Comment by hangingman** [comment]
Okay, I realized it's caused by markdown preview glitch.
ref: https://github.com/cline/cline/issues/578#issuecomment-2425217620

I added following in my project settings.json. And the problem resolved.

```
  "workbench.editorAssociations": {
    "*.md": "default"
  }
```

**Comment by suepradun** [comment]
This is a disgusting question that has bothered me for half a day. I see many people have encountered it as well.

**Comment by tregenza** [comment]
> Okay, I realized it's caused by markdown preview glitch. ref: [#578 (comment)](https://github.com/cline/cline/issues/578#issuecomment-2425217620)
> 
> I added following in my project settings.json. And the problem resolved.
> 
> ```
>   "workbench.editorAssociations": {
>     "*.md": "default"
>   }
> ```

This worked for me. No idea why or what it does but it worked. Thank you.

(Apple M1 VSCode Cline / Roo)

**Comment by Utochii** [comment]
still an issue for me to this day.

`Error writing file:
ENOENT: no such file or directory`
