### ISSUE TITLE
O1 models not supported !

### ISSUE THREAD

**Issue by Ed3scombe3s** [cline/cline#545]
### Which API Provider are you using?

OpenAI

### Which Model are you using?

o1-preview and o1-mini

### What happened?

![Captura de pantalla 2024-10-16 105451](https://github.com/user-attachments/assets/ab2c9b76-16ab-4964-bef7-875f83d8de9f)
O1 models don't accept system prompts. This should be a very easy fix. Also they don't accept streaming either. 

### Steps to reproduce

1 - Choose any o1 model.
2 - Send anything using that mode.

**Comment by saoudrizwan** [comment]
Fixed in v2.0.8, thank you for reporting

**Comment by Ed3scombe3s** [comment]
No it still does not work. At least not when using OpenAi as the API provider.
