### ISSUE TITLE
Temperature should be set to 1 for OpenAI o1-preview model

### ISSUE THREAD

**Issue by hughdidit** [cline/cline#555]
### Which API Provider are you using?

OpenAI

### Which Model are you using?

01-preview

### What happened?

400 Unsupported value: 'temperature' does not support 0 with this model. Only the default (1) value is supported.

>result of any query

### Steps to reproduce

1. Type any query to get result 
2.
3.

### Additional context

Sorry if this is fixed already. I imagine its an easy one to fix but there were no bug reports so it falls on me I suppose :)

**Comment by MrDedalus** [comment]
![Git](https://github.com/user-attachments/assets/f83369a4-72aa-47d1-891b-356ba9738a0d)

**Comment by MrDedalus** [comment]
I have now updated from 2.08 to the latest version and now get this 
![image](https://github.com/user-attachments/assets/3d586f4f-cf49-450e-b88b-b4207278474b)

**Comment by Ed3scombe3s** [comment]
No, it doesn't accept temperature as a parameter, you cannot give it any parameter, it only accepts user and assistant, not even system.
@saoudrizwan if you need acces to an api wiht acces to o1 models, lmk I can give you access to mine so you can address this ongoing issue.
Dm me here:  https://x.com/etiennee_dl?s=21&t=uioS49AmRqsMQgOOrrDSXw

**Comment by hughdidit** [comment]
> No, it doesn't accept temperature as a parameter, you cannot give it any parameter, it only accepts user and assistant, not even system. @saoudrizwan if you need acces to an api wiht acces to o1 models, lmk I can give you access to mine so you can address this ongoing issue. Dm me here: https://x.com/etiennee_dl?s=21&t=uioS49AmRqsMQgOOrrDSXw

I'm not on that fuzagi platform formally called Twitter anymore -- and good riddance but I'm not in a hurry to use o1. Gpt40 will suffice for now. Thanks for the offer though! It will be great when you get it though because the reasoning component is a big step up in capability.

**Comment by saoudrizwan** [comment]
Sorry and thank you for the patience guys! Kinda embarrassing I don't have a high enough tier openai account to test o1 haha, but pls try the latest 2.0.15, it _should_ fix this once and for all.

**Comment by hughdidit** [comment]
Hi!

Thanks for making the changes. I tried it with 01-preview and got this
error:

400 Invalid content type. image_url is only supported by certain models.
To this prompt:

The main() function in call_handler.py is the entry point into my code.
Please parse through it and recommend any improvements. Do not make any
changes; Just recommendations.
Not sure why the 'image_url' ... Just FYI

Thanks,

Hugh Chapman
www.hughdidit.com
(510) 375-4547

*Be initiated! Join the mailing list. Get a free comic.
<http://eepurl.com/gjzCZ1>*

FOLLOW ME:
***@***.***_art <http://instagram.com/hughdidit_art>
*Fan Rewards On Patreon! <http://www.patreon.com/hughdidit> *
