### ISSUE TITLE
Cline doest work with o1 Preview 

### ISSUE THREAD

**Issue by SlimeBswervin** [cline/cline#560]
### Which API Provider are you using?

OpenAI

### Which Model are you using?

o1 Preview

### What happened?

<img width="430" alt="Screenshot 2024-10-17 at 1 13 14 PM" src="https://github.com/user-attachments/assets/fba353e8-9d15-4b20-a562-5ce1deea41cf">

this is throught the latest update inside the Vs Code extension on my Mac

### Steps to reproduce

1. Add open ai api key
2.Choose o1 Preview 
3. Ask anything

**Comment by saoudrizwan** [comment]
Fix in v2.0.15! Please give it a try and re-open if you're still running into issues
