### ISSUE TITLE
Unable to write to .md files

### ISSUE THREAD

**Issue by GitDakky** [cline/cline#578]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Sonnet 3.5

### What happened?

This occurs when I as to create or update a .md file:

Error writing file:
Failed to open diff editor, please try again...

Cline wants to edit this file:

Error
Error writing file:
Failed to open diff editor, please try again...

I apologize for the persistent error. It seems there might be an issue with writing complex content or opening the diff editor. Let's try a simpler approach by writing just the basic structure of the architecture without the Mermaid diagram. We'll use plain text to describe the components and their relationships.

### Steps to reproduce

1. Eg. Generate a readme.md
2. Eg. Update to TODO.md
3. Any creation or update to a .md

### Relevant API REQUEST output

```shell
Provided above
```

### Additional context

This started to occur in the last week. Never had this issue in previous versions of Claud Dev. Currently using the latest version of Cline

**Comment by GitDakky** [comment]
Update - I think I have found the conflict. Only occurs when .md preview is on. I turned it off and the issue resolved itself.

**Comment by lin2code** [comment]
If md file open default is preview, then right click editor tabbar, choose open editor method->.md file->text.
Then cline edit md file will not fail.
