### ISSUE TITLE
Code Generation Extension Freezes When Using PHP 8 Attributes

### ISSUE THREAD

**Issue by eprofos** [cline/cline#608]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

anthropic/claude-3.5-sonnet

### What happened?

When coding in PHP 8 and using attributes such as `#[ORM\Entity(`, `#[ORM\Table(`, or `#[Route(`, the code generation extension frequently hangs or becomes unresponsive. This issue occurs consistently (Often but not always) after typing these attribute declarations, hindering the development process.

### Steps to reproduce

1. Generate a PHP file with the code generation extension enabled.
2. When begin typing an attribute, e.g., #[ORM\Entity(.
3. Observe that the extension freezes or stops responding.

**Comment by entrepeneur4lyf** [comment]
I think that may be your linter because I have been using them all day and not seen this issue. Maybe check that. Do you have more than 1 enabled?

**Comment by eprofos** [comment]
> I think that may be your linter because I have been using them all day and not seen this issue. Maybe check that. Do you have more than 1 enabled?

Since I disabled the extension https://marketplace.visualstudio.com/items?itemName=liamhammett.temphpest, everything has been working fine. I think you're right.
