### ISSUE TITLE
It won't connect to the api.

### ISSUE THREAD

**Issue by 117649** [cline/cline#614]
### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

gpt-4o

### What happened?

![image](https://github.com/user-attachments/assets/2760d6a1-6d52-4d8e-a6d7-fa9cfbd3ceb5)
![image](https://github.com/user-attachments/assets/6fbcaae6-e481-489b-a850-27a0fc0513d3)

It has been tested in the terminal that the api is connectable.
However extension keep say connection error.
wtf is it doing?
I don't get any log or output on what request is it making or if it making any request at all?

### Steps to reproduce

1. Install from market
2. Fill in api settings
3. boom

**Comment by 117649** [comment]
Switched to http and it getting through.
What the hell. Curl can make https work.

**Comment by sssuperman** [comment]
Also have same issue. Curl command connectivity has been confirmed. But show connection error

**Comment by saoudrizwan** [comment]
I am sorry but I'm not sure how I would fix this issue. The extension just uses openai's library so if the URL doesn't work with that, there isn't much I can do. It might be worth opening an issue on their repo to see if they can shed some light here.

**Comment by sssuperman** [comment]
Where could I get get log with http information?
