### ISSUE TITLE
Cline hanged on changing model in same provider

### ISSUE THREAD

**Issue by teetangh** [cline/cline#629]
### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

llama-3.2-3b-preview to gemma2-9b-it

### What happened?

I just changed from to 
llama-3.2-3b-preview to gemma2-9b-it in groq, the first prompt worked, the second did not.
<img width="280" alt="image" src="https://github.com/user-attachments/assets/4175ec4d-40a1-41f9-9f7f-d93a57db413b">

### Steps to reproduce

listed above

**Comment by saoudrizwan** [comment]
You're likely seeing this because gemma2-9b-it is having trouble, 9b is small and Cline doesn't work great with models that weak. Pls try to repro with claude 3.5 sonnet, and if you run into the same issue feel free to re-open.
