### ISSUE TITLE
Incorrect models listed in AWS Bedrock outside US

### ISSUE THREAD

**Issue by sammcj** [cline/cline#632]
### Which API Provider are you using?

AWS Bedrock

### Which Model are you using?

anthropic.claude-3-sonnet-20240229-v1:0

### What happened?

After selecting the region of AWS Bedrock, the list of models is not updated and displays models available in the us-west-2 region instead.

Regions such as Australia (ap-southeast-2) are still stuck running mid-low end models that are coming up to a year old, if possible we'd select to use us-west-2 but many of us aren't able to due to data sovereignty laws.

![SCR-20241028-mpdh](https://github.com/user-attachments/assets/d440da93-8583-40aa-bf8d-6f1c80577a6c)

### Steps to reproduce

1. Set region to ap-southeast-2 (or any region that doesn't have the models available in us-west-2)
2. Expect to see the list of available models in-region / account (e.g. `anthropic.claude-3-sonnet-20240229-v1:0`)
3. Instead see models available in us-west-2

### Additional context

_Not pictured: Many months of complaining to AWS about the lack of investment in Bedrock in Australia_

**Comment by saoudrizwan** [comment]
> Regions such as Australia (ap-southeast-2) are still stuck running mid-low end models that are coming up to a year old

That is really so tragic, I am so sorry 😅
