### ISSUE TITLE
Confusing Claude 3.5 sonnet (new) name in Open Router

### ISSUE THREAD

**Issue by it-sha** [cline/cline#634]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

 Claude 3.5 sonnet (new). Probably

### What happened?

Could you recommend wich model should I choose for Claude 3.5 sonnet 20241022 from Open Router?
Just regular `anthropic/claude-3.5-sonnet` or `anthropic/claude-3.5-sonnet:beta`?

![image](https://github.com/user-attachments/assets/64221390-b5e6-4872-ae6b-6ffe3c05250e)

### Steps to reproduce

1. Click settings
2. Select open router
3. type "claude-3.5

### Additional context

Cline v2.0.19

**Comment by PhunkyBob** [comment]
If you got to [this page](https://openrouter.ai/anthropic/claude-3.5-sonnet), you see that the model `claude-3.5-sonnet` was created on "Oct 22" in OpenRouter --> this is the new one.
On [this page](https://openrouter.ai/anthropic/claude-3.5-sonnet:beta), you see that the model `claude-3.5-sonnet:beta` was also created on "Oct 22" --> this is also the new one, but "self-moderated".

**Comment by saoudrizwan** [comment]
They both point to the latest oct 22 model, there is now a new `anthropic/claude-3.5-sonnet-20240620` that points to the old version. (Confusing I know!)

**Comment by spirelab** [comment]
Also it's not as intelligent as the on from https://www.anthropic.com/ it's self! Specifically in coding, I notice a difference,the api from anthropic is more efficient in coding don't know why! If it's the same

**Comment by elogicuk** [comment]
> Also it's not as intelligent as the on from https://www.anthropic.com/ it's self! Specifically in coding, I notice a difference,the api from anthropic is more efficient in coding don't know why! If it's the same

hmmmm thank you im glad someone else spotted this. i also think this im working with python and qt6
whats going on?

**Comment by goforu** [comment]
<img width="374" alt="image" src="https://github.com/user-attachments/assets/7f796b24-0fc2-43dc-9d69-93b2641a62ce" />
<img width="377" alt="image" src="https://github.com/user-attachments/assets/0c26137a-5543-4f4a-8f08-45cc2d723726" />
Why the model says, it's Claude 2...

**Comment by michelbaas** [comment]
Why can you only choose Claude models in Cline via OpenRouter? 

It seems odd—there's no apparent option to use other models via OpenRouter in Cline, unlike with Continue.dev, where it's straightforward. There, you can even assign a separate API key for each model you use through OpenRouter if you want. 

Am I missing something—is this even possible?
