### ISSUE TITLE
dosnt like anthropic API key gives error

### ISSUE THREAD

**Issue by bob10042** [cline/cline#638]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

sonnet 3.5 new model

### What happened?

APi invalid key the key works on other models and using openrouter

### Steps to reproduce

1.trying to use cline
2.
3.

**Comment by saoudrizwan** [comment]
Please make sure you've selected the correct API provider, I'm really not sure how to help here but I suggest using openrouter if you're having trouble with anthropic. Openrouter lets you sign in with a click of a button

**Comment by stevejford** [comment]
Same issue here this a problem. Have to useopen router
