### ISSUE TITLE
Cline not recognizing input / tasks from qwen2.5-coder

### ISSUE THREAD

**Issue by Git-User76** [cline/cline#639]
### Which API Provider are you using?

Ollama

### Which Model are you using?

qwen2.5-coder

### What happened?

Testing Cline + qwen2.5-coder.

The model works fine in the terminal and outputs code as expected, but when using Cline it just keeps showing 'The user has not explicitly stated a task yet...', no matter the task requested.

Running qwen2.5-coder directly from the terminal
![Screenshot from 2024-10-28 15-25-13](https://github.com/user-attachments/assets/01570690-7453-4bc4-81b6-d417c00e084e)

Running from vscode
![Screenshot from 2024-10-28 15-26-06](https://github.com/user-attachments/assets/b3ca58c4-af94-4c68-b2e6-0b0fafcd5ccc)

cline - vscode settings
![image](https://github.com/user-attachments/assets/a98f9012-04c0-4063-8e31-500d7cf92629)

Tried:
- Reinstalling Cline but no luck. Same issue.
- Using Claude API works as expected. No issue.

### Steps to reproduce

1. Tried multiple types of tasks with qwen2.5-coder, from complex to simple. Same issue.

**Comment by Git-User76** [comment]
Could the issue be related to "API request cancelled"? The request is cancelled automatically after thinking for some time

**Comment by Git-User76** [comment]
nvm. Same issue.
![image](https://github.com/user-attachments/assets/5845d482-2862-4cf3-9134-93ad1a6d2fdc)

**Comment by maryasov** [comment]
try this model `ollama run maryasov/qwen2.5-coder-cline`
this is original `qwen2.5-coder:7B` with fixed prompt templates

**Comment by Git-User76** [comment]
thnks @maryasov , it works with cline, but extremely slow. Might be something with the app itself or my config (need to investigate further). Running directly from the terminal is much faster.

The modded model is twice the size and more straightforward / simpler
Here's a comparisson output between them:

![image](https://github.com/user-attachments/assets/56b21128-0fc0-4e8b-aee8-c7504524c8d8)

**Comment by maryasov** [comment]
> The modded model is twice the size

Try `ollama run maryasov/qwen2.5-coder-cline:7b-instruct-q2_K` Q2_K quantized version
Its 3GB size. Works faster than `maryasov/qwen2.5-coder-cline` which has quantization Q8_0 and size 8.1GB

**Comment by Git-User76** [comment]
thanks. it worked :)

**Comment by silversonicaxel** [comment]
In my MacBook Air M3 16 GB both `maryasov/qwen2.5-coder-cline:7b-instruct-q2_K` and `maryasov/qwen2.5-coder-cline:7b-instruct-q4_K_M` results still very slow.
Ideas?
