### ISSUE TITLE
gemini 1.5 Flash and gpt4o not updating code when they say they have

### ISSUE THREAD

**Issue by Jalicky765** [cline/cline#640]
### Which API Provider are you using?

Google Gemini

### Which Model are you using?

1.5 flash & GPT4o

### What happened?

So I specified the changes I want to be made it outlines the changes it will make it says it has implemented those changes and when the new page is uploaded none of those changes have an updated also I can see when the code is being written it looks like it's more being scanned across and there aren't any visible changes happening to the code whereas when a model is rewriting or changing code I can see the changes being updated in the code spaces box this does not happen and it just scan through although it does say that it has made the changes which it does not

### Steps to reproduce

1.
2.
3.

**Comment by saoudrizwan** [comment]
This unfortunately is just a case of 'models being dumb' editing a file without actually making any new changes. Not much I can do on the extension's side to fix this.
