### ISSUE TITLE
Cline doesn't "see" terminal output

### ISSUE THREAD

**Issue by jtac** [cline/cline#641]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet 20241022

### What happened?

I'm having trouble with Cline not "seeing" what's in the terminal, responses are good but I'm having to copy and paste terminal responses back to Cline for it to work.

In this example, Cline decides server is not running even though it is, then cannot see the output by "ls"

This is in WSL2 (ubuntu 24.04) under Win11, Terminal is Bash (default)

```
Cline wants to execute this command:
lsof -i :3000

No active server detected on port 3000. I'll start the development server to test the authentication flows.

Cline wants to execute this command:
cd client && npm run dev

I suspect you might have trouble seeing terminal output, test by listing the content of the current directory and repeating it back to me

I'll list the contents of the current directory to verify I can see the terminal output.

Cline wants to execute this command:
ls

You're right - I'm not seeing the terminal output. Let me proceed with testing the auth flows by launching the site in the browser and checking the functionality.

Cline wants to use the browser:
http://localhost:3000

```
![image](https://github.com/user-attachments/assets/98c1b0a3-f005-4471-87f8-3e66d3d1478e)

### Steps to reproduce

1.
2.
3.

**Comment by jmartsch** [comment]
I can confirm this. I am also on Windows 11 in a WSL2 Ubuntu environment.

**Comment by dtgagnon** [comment]
I'd like to add to this that using an ephemeral nix-shell will cause the cline extension to believe it is incompatible. I've had no issue with the NixOS WSL2 instance on the zsh shell, but once we load into the nix-shell, the problem begins (the nix-shell is still running via zsh).

**Comment by jtac** [comment]
I moved back out of the WSL for now as I really like to use Cline :D

**Comment by existentialstudios** [comment]
With my custom powershell profile, and now the default profile, if it takes longer than about 1000ms to load, cline won't wait for it. At least thats what I'm noticing. It was working for a bit after i disabled my custom profile, but now even my default profile is taking 2000+ms to load, not cline's fault but it should wait for the shell to load...

**Comment by jtac** [comment]
for me the problem isn't the response time, the output is near instant into the terminal but cline still ignores it

when there's something that takes time, like launching an npm server, cline nicely waits until it's done or you can click 'continue while running'

**Comment by existentialstudios** [comment]
I've had a problem similar that while using it on idx.dev, but my current
issue with shell interaction seems to stem from me going ham on my
config/profile scripts. I've also noticed lately that cline spawns a new
terminal Everytime it wants to run a command, is that happening to you as
well?

**Comment by saoudrizwan** [comment]
Hello! This is a known issue with VS Code's shell integration API where some commands (especially immediately returning ones) don't pass the output back to the Cline extension.

Please follow the instructions in this repo to see if it helps solve the issue, and if not I would appreciate you creating an issue there so that I can report it to the VS Code team. https://github.com/saoudrizwan/shell-integration-problems

Thank you

**Comment by jtac** [comment]
thanks @saoudrizwan the step listed for 5. For Windows PowerShell users actually also fixes the problem when running Ubuntu in WSL2 under windows 11, so the documentation might benefit from an update

**Comment by delorenj** [comment]
If anyone is here looking for a bandaid solution, I added a rule to ensure each time a terminal command is executed,  output is piped to a log.

`For some reason, the vscode terminal output is invisible to you. Pipe output to a file and examine that instead`

**Comment by joshwand** [comment]
I improved the above somewhat:

`For some reason, the vscode terminal output is invisible to you, redirect stderr to stdout, tee the output to a file, and examine that instead.`

**Comment by nipe0324** [comment]
In my case, Cline was able to "see" the terminal results by switching from `zsh` to `bash`.

Details:

- Using the terminal with `zsh` (`prezto`) as default
- Unable to retrieve the results of commands executed by Cline
- Changed Cline’s terminal from `zsh` to `bash` (by running the `bash` command in Cline's terminal)
- Successfully retrieved the results of commands executed by Cline

**Comment by yoshkinkod** [comment]
@nipe0324 how did you change only Cline's terminal?

**Comment by jtac** [comment]
Update as OP: personally I havent had this issue for a while, it disappeared in one of the updates. However people seem to still be updating the issue with comments so maybe it would be a good idea to take this onto the "things to think about" roadmap and see if terminal handling requires some improvements.

**Comment by askolesov** [comment]
Same for me - output from some commands is visible, from others - not:

- First, I ran `echo "Hello, World!"` - The command executed successfully, but the actual output wasn't visible in the response.
- Then I ran `ls -la` - This command showed full terminal output, displaying all files and directories in the current directory with their details.
- I tried another `echo` command - Again, the command executed but without showing the output.
- Finally, I ran the `date` command - This showed the current date and time output.

**Comment by braxton-mills** [comment]
> I just use this and it seems to fix the issue. I'm guessing there's some race condition happening
> 
> ```
> Anytime you use the terminal, make sure to append an `&& sleep 1`, otherwise you won't be able to view the result
> ```

This worked like a dream for me combined with a version of [nipe0324](https://github.com/nipe0324)'s solution. Using Cursor + Cline on a wsl2 Ubuntu distro.

In VSCode/Cursor:

1. CTRL+SHIFT+P -> Terminal: Select Default Profile -> bash
2. Open Cline settings and paste into the custom instructions: `Anytime you use the terminal, make sure to append an `&& sleep 1`, otherwise you won't be able to view the result`
3. Ensure your .bashrc doesn't have any startup scripts that will delay its initialization time to avoid a race condition with cline.

**Comment by Cosmic-Skye** [comment]
Happens to me all the time on both Windows and Mac with Claude 3.7.

**Comment by yummydum** [comment]
Also getting the same problem when I use cline in vscode dev container. I am using the official image (mcr.microsoft.com/devcontainers/python:3.11).

**Comment by DLRACT** [comment]
This keeps on happening with on W11 VS Code using a PowerShell terminal, latest version of Cline and Claude.

**Comment by bg-jasonyuan** [comment]
One thing that worked for me (zsh on OSX) was to manually [configure terminal integration](https://code.visualstudio.com/docs/terminal/shell-integration) in VSCode. Specifically, I added the line
```[[ "$TERM_PROGRAM" == "vscode" ]] && . "$(code --locate-shell-integration-path zsh)"```
to the top of my `.zshrc` file.

**Comment by DLRACT** [comment]
The sleep workaround only works if the terminal complete the output within the sleep period, otherwise the same issue happens, so not really a solution at all.

**Comment by antfris** [comment]
I found a working workaround, in cline settings add this as a custom instruction:

"For some reason you are unable to see the output of terminal commands, a workaround i've found is to type bash before you are going to use the terminal and then exit after you have executed the command. when you use the terminal, first execute `bash` then after your command execute `exit` and you should receive the output."

**Comment by DLRACT** [comment]
The best workaround I have found thus far is to rather let it create PowerShell scripts and those write to log files that can then be interrogated. I changed my settings to not auto executes command so I can intervene. It also seems to read terminal output better when executed from scripts. Bonus is you only create the script once so less calls to LLM to redo those each time.

**Comment by EzzatQ** [comment]
If you’d like to preserve your existing terminal configuration while fixing Cline's integration with the VSCode terminal, you can follow these steps:

1. Create a minimal zshrc file specifically for Cline, e.g., `~/.cline/.zshrc`, with just the VSCode terminal integration line:
```
[[ "$TERM_PROGRAM" == "vscode" ]] && . "$(code --locate-shell-integration-path zsh)"
```
2. Open VSCode settings.json (`Cmd` + `Shift` + `P` → `Preferences: Open User Settings (JSON)`)
3. Add a custom terminal profile under the `"terminal.integrated.profiles.osx"` setting (or the corresponding key for your OS):
```
"zsh_cline": {
  "path": "zsh",
  "args": ["-l"],
  "env": {
    "ZDOTDIR": "~/.cline/.zshrc" // path to your custom zshrc
  }
}
```
4. Save and restart VSCode
5. Set the default terminal profile to zsh_cline: `Cmd` + `Shift` + `P` → `Terminal: Select Default Profile` → Choose `zsh_cline`

With this setup, Cline should be able to access and display terminal output properly. At the same time, you can still open a separate terminal using your regular, fully customized profile by switching the terminal profile as needed.

**Comment by monkpit** [comment]
It seems (from my testing) that commands with SHORT output do not work reliably, longer output usually works for the most part.

Particularly when cline tries to run something like `which uvx | echo "uvx not found"` it never continues the task because it cannot see anything.

I tried to narrow it down by having cline use `seq` or `echo` to output different lengths and repeat what it could see back to me. It was reliably missing the 1st line on most of the output.

**Comment by KnowhereFern** [comment]
Crazy that this issue is still happening in may of 2025. If you google around a lot of different people posting the same error. and its mark as closed, you can duplicate so easily on a clean install of windows.

**Comment by BearThreat** [comment]
Just wanted to add that this is still an issue

**Comment by subhashisbhowmik** [comment]
This issue should not be closed. In mac: It works with bash, in win10 + wsl it also worked for me with bash and powershell. But in W11 it doesn't work at all, I have tried gitbash, powershell (5, 7 both), wsl + zsh, wsl + bash
Sometimes it shows the message Shell Integration Unavailable, sometimes it doesn't but still the output of the command isn't included in the context

Please reopen this

**Comment by enciyo** [comment]
@subhashisbhowmik +1

**Comment by wilkice** [comment]
still have this error in WSL. cline version: `v3.27.2`

**Comment by DavidMetcalfe** [comment]
Still seeing this issue in VS Code v1.104.0, Cline v3.28.3

Doesn't change when you Ctrl+Shift+P and set the terminal default profile.

**Comment by emtiazzahid** [comment]
For me, changing the terminal for cline Default (zsh) to bash solved the issue

**Comment by ShadabFaiz** [comment]
> for me changing the terminal for client Default (zsh) to bash solved the issue

this one works on macos also
