### ISSUE TITLE
Revert Block Feature Causing Duplicate Code

### ISSUE THREAD

**Issue by techcow2** [cline/cline#647]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

Please check the revert block feature for possibly duplicating existing code instead of replacing it.

### Steps to reproduce

Revert a chunk of code. The response is always "It looks like there is duplicate....."

**Comment by saoudrizwan** [comment]
The revert block button is a vs code feature, not a cline feature. Can you pls post screenshots of before and after you use the button? I know some other users mentioned that the latest version of vs code revert block button was buggy compared to older versions

**Comment by techcow2** [comment]
Thank you...I think I made a mistake with this one as it seems to be working fine now.
________________________________
