### ISSUE TITLE
Cline doesn't work with Codestral from mistral.ai

### ISSUE THREAD

**Issue by gregid** [cline/cline#665]
### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

codestral/codestral-latest

### What happened?

I can't get codestral from mistral.ai to work with cline:
https://console.mistral.ai/codestral
(subscription - currently free to use)

### Steps to reproduce

1. Using for baseURL: `https://codestral.mistral.ai/v1/chat/completions`
2. Trying both `codestral/codestral-latest` and `codestral-latest` for model
3. Type a message

### Relevant API REQUEST output

```shell
404 status code (no body)
```

**Comment by saoudrizwan** [comment]
Closing as duplicate of https://github.com/cline/cline/issues/582

**Comment by alfredwallace7** [comment]
Please reopen as https://github.com/cline/cline/issues/582 does not provide a solution.
