### ISSUE TITLE
Why is the qwen2.5-code model not supported?

### ISSUE THREAD

**Issue by kim114** [cline/cline#667]
### Which API Provider are you using?

Ollama

### Which Model are you using?

llama3.1:70b

### What happened?

Why is the qwen2.5-code model not supported? This model is also very suitable for home PC in terms of performance.Also has the function of offline use

### Steps to reproduce

Reports an error and prompts that Claude 3.5 is required

**Comment by saoudrizwan** [comment]
Hello! Ollama qwen models are supported, although you may not get the best results. I suggest trying a less quantized version of the model (larger size, requires more vram) for the best results, but ultimately it's hard to gaurantee any results from models that aren't claude 3.5 sonnet or gpt4o. I am actively trying to make the extension's prompts less complex to hopefully produce better results with less capable models.
