### ISSUE TITLE
AWS GovCloud region support for Bedrock

### ISSUE THREAD

**Issue by r0b0techcloud** [cline/cline#669]
### Which API Provider are you using?

AWS Bedrock

### Which Model are you using?

anthropic.claude-3-5-sonnet-20240620-v1:0

### What happened?

Cannot select us-gov-west-1 as a region when selecting AWS Bedrock as API Provider. Anthropic Claude models are now supported in GovCloud.

### Steps to reproduce

1. Select AWS Bedrock for API Provider
2. Enter valid AWS Access Key and Secret Key
3. Select AWS Region drop down

### Relevant API REQUEST output

```shell
N/A
```

**Comment by AMHesch** [comment]
Issue is actually with default URL used in the [Anthropic Bedrock SDK](https://github.com/anthropics/anthropic-sdk-typescript/blob/1043b48abc82586f4fe6f75aa86559878c5adaf4/packages/bedrock-sdk/src/client.ts).  Need to configure an environment variable for the ANTHROPIC_BEDROCK_BASE_URL and put an Issue/PR upstream.

**Comment by saoudrizwan** [comment]
Thank you for looking into this @AMHesch!
