### ISSUE TITLE
DISCORD Broken

### ISSUE THREAD

**Issue by skoenman** [cline/cline#670]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

claud

### What happened?

Discord link is broken please update 

### Steps to reproduce

1. click link says invalid
2.
3.

**Comment by mdp** [comment]
There are two links to the Discord in the README, both go to https://discord.gg/cline

I tested it on my end and it did seem to work, do you have anymore information about what's not working?

**Comment by saoudrizwan** [comment]
Closing because the discord link works (try opening the discord link on your phone?)
