### ISSUE TITLE
When using "Anthropic" as the provider, when I click on "Select a model..." in model selection in settings, nothing happens.

### ISSUE THREAD

**Issue by daffi7** [cline/cline#677]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

I would like to use older versions of Claude 3.5 sonnet too, specifically 20240620. The "Select a model..."  option in settings does not work (nothing happens). 
Reason: Anthropic imposes strict rate limits, but these are independent for each model. So when my limits for sonnet 20241022 are reached, Anthropic still allows to use the older version of sonnet as the rates are separate. 
Can you please fix the "Select a model..."  functionality when using "Anthropic" as provider? 
Using Claude models through OpenRouter is not the same, so I think resolving this bug with "Anthropic" as provider would benefit many, many users of your extension. 

### Steps to reproduce

1. Go to Settings
2. Choose "Anthropic" as provider
3. Click on "Select a model..." - nothing happens

I am running MacOS Sonoma 14.2 and "Visual Studio Code", but I suspect it will not be a platform-specific problem.

### Additional context

Anthropic API is heavily rate limited. Anthropic counts tokens separately for different models and model versions it provides.

**Comment by maxceem** [comment]
I came across the same issue. It would be nice to be able to choose other models with their own limits, to get more daily requests with Cline:

<img width="1180" alt="image" src="https://github.com/user-attachments/assets/d9e578ff-4c06-43a8-b671-32ad4c39ce4a">

But Cline allows selecting only 3:

<img width="362" alt="image" src="https://github.com/user-attachments/assets/9578717a-bdba-4656-82c9-f1dcfc011ada">

**Comment by KJ7LNW** [comment]
+1. You might consider doing yourself a favor and future-proof Cline, because this issue is likely to show up again in different ways: 

it would be a simple field to add in your software - always support custom model name overrides!

thank you for your help!

**Comment by KJ7LNW** [comment]
quick hack: 

perl -p -i -e 's/claude-3-opus-20240229/claude-3-5-sonnet-20240620/g' ~/.vscode/extensions/saoudrizwan.claude-dev-2.1.3/{dist/extension.js,webview-ui/build/static/js/main.js}

**Comment by saoudrizwan** [comment]
@KJ7LNW that is a really clever trick, I wonder if cline came up with that? Kind of funny how cline can modify its own code this way haha...

I removed the old model ID because I figured it would be confusing to users and they might end up choosing the older version on accident. If the problem here is running into rate limits, I highly suggest you use OpenRouter–same exact service as Anthropic but without the rate limits, way more model offerings, and easier billing.

**Comment by KJ7LNW** [comment]
> I wonder if cline came up with that? 

no just grep'd the tree

> OpenRouter

neat!

**Comment by daffi7** [comment]
> @KJ7LNW that is a really clever trick, I wonder if cline came up with that? Kind of funny how cline can modify its own code this way haha...
> 
> I removed the old model ID because I figured it would be confusing to users and they might end up choosing the older version on accident. If the problem here is running into rate limits, I highly suggest you use OpenRouter–same exact service as Anthropic but without the rate limits, way more model offerings, and easier billing.

Unfortunately, OpenRouter does not offer the same quality. Would it be possible to add the old version of Sonnet 3.5 to the tree and just put something in parentheses so that it is more clear to the user? It would be of great help.

**Comment by KJ7LNW** [comment]
always support custom model name overrides! just give us a "custom" field, so we can put in the model name from the provider (for **all** providers).

**Comment by daffi7** [comment]
> always support custom model name overrides! just give us a "custom" field, so we can put in the model name from the provider (for **all** providers).

Excellent idea! Simple, very helpful, future-proof.
Would it be possible to implement?

**Comment by KJ7LNW** [comment]
Re-open ticket, or copy-paste incomplete parts to new ticket?

**Comment by KJ7LNW** [comment]
>  Would it be possible to implement?

of course it is possible! you might even be able to get cline to do it!
