### ISSUE TITLE
OpenAI Compatible Option Requires API Key

### ISSUE THREAD

**Issue by techcow2** [cline/cline#680]
### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

n/a

### What happened?

The OpenAI compatible option requires an API key, making it so you can't use local LLM's that don't provide the option of an API key. Removing this requirement would be great so that we have the option of using local LLM models.

### Steps to reproduce

1. Click the gear icon
2. Select OpenAI compatible for the API provider
3. Enter the server URL and other information (without API key)

**Comment by Jasmin68k** [comment]
I use LiteLLM (OpenAI compatible proxy) with `http://localhost:4000` as `Base URL`.

Whatever I enter for `API Key` and `Model ID` is just ignored.

I think this might work with a local model, too, haven't tried though.

**Comment by techcow2** [comment]
Thank you I will try that.
________________________________

**Comment by Jasmin68k** [comment]
Clarification: If it doesn't work directly, using LiteLLM as proxy you should be able to get it to work, since LiteLLM supports Ollama.
