### ISSUE TITLE
Using "computer use" instead of viewing the lcoal web page

### ISSUE THREAD

**Issue by mikes-bowden** [cline/cline#681]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Claude 3.5 Sonnet Beta Latest

### What happened?

Since the last update, Cline has tried to view the currently running app's web page multiple times but uses Computer Use instead of viewing the page as it normally would have.

Each time, my API costs jump a good bit. I haven't used Computer Use, but I didn't expect it to be so expensive. I've seen a $1+ jump just from it trying to load the website. I assume it's trying to use Computer Use?

Is there any way to disable it? I don't believe I'll use it for anything.

### Steps to reproduce

I believe it happens if it initiates viewing a locally running page. If you provide the link, it seems fine.

**Comment by saoudrizwan** [comment]
Hi Mike! I need to work on reducing how often cline uses the browser, but you can tweak this yourself or disable it entirely by adding it to Settings > Custom Instructions, something along the lines of "do not use the browser_action tool" or "only use the browser_action tool at the end of the task if absolutely necessary"
