### ISSUE TITLE
Openrouter Input and Output Token pricing unclear

### ISSUE THREAD

**Issue by Freffles** [cline/cline#686]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

meta-llama/llama-3.2-90b-vision-instruct

### What happened?

The token prices that Cline displays appear to be for the lowest priced provider but there is quite a gap between the low price and the high price. How does the user know what is likely cost of a task?

Cline indicates this: 
Max output: 4,096 tokens
Input price: $0.06/million tokens
Output price: $0.06/million tokens

OpenRouter indicates this:
![image](https://github.com/user-attachments/assets/c321c33e-aaa4-4f42-b5b7-8a433e6921c9)

### Steps to reproduce

Select OpenRouter and meta-llama/llama-3.2-11b-vision-instruct in Cline settings

**Comment by saoudrizwan** [comment]
Cline uses OpenRouter's models API (https://openrouter.ai/docs/models) to get the latest prices. The prices displayed will be the best available, there isn't much more granularity offered by the API.

**Comment by lynxul25** [comment]
Is there any way to force one specific provider to be used? Sometimes the price differences are.. well.. crazy.

![Image](https://github.com/user-attachments/assets/d6d1c656-dbf8-4c01-a851-833687816034)
