### ISSUE TITLE
Issue with Bedrock models with cross-region inference

### ISSUE THREAD

**Issue by mykemd** [cline/cline#689]
### Which API Provider are you using?

AWS Bedrock

### Which Model are you using?

anthropic.claude-3-5-sonnet-20241022-v2:0

### What happened?

Requests fail with error message
```
400 Invocation of model ID anthropic.claude-3-5-sonnet-20241022-v2:0 with on-demand throughput isn’t supported. Retry your request with the ID or ARN of an inference profile that contains this model.
```

with models that only support inference profile

### Steps to reproduce

1. Open Plugin
2. Select anthropic.claude-3-5-sonnet-20241022-v2:0 model
3. enter AWS connection information
4. Enter something in the chat window

### Additional context

There is no way to specify the inference profile for the model and there is no default profiles used for the model. Bedrock has some default profiles created for these models for us for example
us.anthropic.claude-3-5-sonnet-20241022-v2:0

**Comment by snsa-kscc** [comment]
Having the exactly same problem.

**Comment by saoudrizwan** [comment]
v2.1.4 now as a cross-region inference toggle that prefixes the model id with the region identifier. Please let me know if this fixes the issue!

![image](https://github.com/user-attachments/assets/0bb80462-88c2-43c7-a991-feed8452969e)

**Comment by marketcalls** [comment]
> @snsa-kscc @lmb627 @lukemcgregor v2.1.4 now has a cross-region inference toggle that prefixes the model id with the region identifier. Please let me know if this fixes the issue!
> 
> ![image](https://private-user-images.githubusercontent.com/7799382/384106405-0bb80462-88c2-43c7-a991-feed8452969e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMjQ4NTgsIm5iZiI6MTczMTEyNDU1OCwicGF0aCI6Ii83Nzk5MzgyLzM4NDEwNjQwNS0wYmI4MDQ2Mi04OGMyLTQzYzctYTk5MS1mZWVkODQ1Mjk2OWUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMDlUMDM1NTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTMzMzU3YWVmOWFlZjM5OTU4NTA1M2IyNDM3MDVjYzBjNmM0YjQ1YTIxOTc4ZTQzOTQ5Y2RiOGQ0ZmY3MGE2NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.0X9FfLm0Qnm5YcDJBhLGpF0mKYdQjY6_d5kWEQGHsOo)

That fix my issue and now able to connect

<img width="418" alt="Screenshot 2024-11-09 at 9 27 23 AM" src="https://github.com/user-attachments/assets/f2a94bee-6447-42e3-938c-37f5d6bd7d1b">

**Comment by usathyan** [comment]
Good for you! any ideas where i can see debug/error message details I get?
