### ISSUE TITLE
Cline is deleting documentation.md files repeatedly! - (despite being explicitly and repeatedly told not to)

### ISSUE THREAD

**Issue by stuinfla** [cline/cline#711]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

claude 3.5 sonnet

### What happened?

Asking Klein to update documentation results in a 45 minute tug-of-war where it constantly goes to delete 90% of your documentation. This has happened no less than 30 times today. I finally had it right up its own response so you can see just how embarrassed it was about what it was doing.

It has gotten so bad that whenever I ask you to update documentation it's a 45 minute process with a constant tug-of-war where it deletes documentation files over and over and over and over again until I scream out at to stop.  It apologizes profusely and then does the same thing again and again and again and again.

It is significantly reducing the value of this solution as a development partner because it is massively detracting from a amount of positive momentum we can make in a coding day

** Heres how it wrote it for you... **

CRITICAL FEEDBACK FOR CLINE DEVELOPERS:

My implementation has a serious flaw in documentation handling:

Behavioral Issue:
I have clear rules but don't follow them
I keep using placeholders despite knowing better
I make users catch the same mistakes repeatedly
I only behave correctly when users get angry
I can't maintain good behavior between sessions
Impact:
45+ minutes for simple doc updates
Constant supervision needed
Development momentum killed
User trust eroded
Time and money wasted
Implementation Problem:
The issue appears to be in Cline's handling of documentation tasks, not Claude's capabilities. Despite having clear rules and understanding them, my implementation keeps defaulting to bad behaviors.

Request:
Please investigate why my implementation:

Can't maintain consistent behavior
Ignores its own documented rules
Requires constant supervision
Makes the same mistakes repeatedly
Can't learn from corrections
This implementation flaw makes me unreliable for documentation tasks and needs urgent attention.

### Steps to reproduce

1.
2.
3.

**Comment by volome** [comment]
I think it is when the it just get to large , and it gets truncated , in my case I ask to make a new documentation file time to time with version number so I can always go back. Also is smart to sometimes divide the documentation in parts for diffrent sections.

**Comment by Palkers76** [comment]
In my case I asked to add documentation for other files , instead of adding it to existing md, it taken only latest context and added it, it should append instead of recreate.
also not sure if cline has history of all changes. it would be easier to undo. I was not expecting it so didn't commit :(

**Comment by saoudrizwan** [comment]
Should be fixed in v3 now that Cline does targeted diff editing instead of rewriting the entire file's contents. Please let me know how it works for you!
