### ISSUE TITLE
404 or "401 status code (no body)"

### ISSUE THREAD

**Issue by Versfragment** [cline/cline#720]
### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

Qwen/Qwen2.5-Coder-32B-Instruct

### What happened?

Hey there,
I tried to add the openai compatible api from hyperbolic and also from deepinfra. Somehow none of them is working.
I tried all kinds of url shortening but usually it should be something like "https://api.hyperbolic.xyz/v1/".
Using hyperbolic I get the 401 no body error and deepinfra gives the 404 no body error.

I do not have any issues using Openai or Anthropic, but it seems to be a problem using any openai compatible.
I am using version v2.1.5 at this moment but somehow even downgrading wont help me out here.

### Steps to reproduce

1. Set API Prov. to OpenAI compatible
2. Set the API endpoint data
3. Try to use it.

**Comment by skoenman** [comment]
Problem happens with https://deepinfra.com aswell ...not sure if it has something to do with the model itself maybe??

**Comment by synth3** [comment]
I am seeing the same problem with claude-3.5-sonnet. I already tried older versions up to 2.1.3. Can I maybe do something to get some log output (as it may be some problem on our side)? Currently the VSCode extensions log only shows:

```
Cline extension activated
ClineProvider instantiated
Resolving webview view
Webview view resolved
```

**Comment by famirHossein81** [comment]
I had exactly the same issue

**Comment by willieseabrook** [comment]
I am getting the same behavior on linux with DeepInfra OpenAPI. Instead clearing out the cache, vs code data etc doesn't work. Nothing works, no errors in logs just 404 back.

**Comment by YehorI** [comment]
Similar behaviour with custom Anthrophic provider https://api.proxyapi.ru/anthropic/v1. 
Just 404 without explanations nevertheless Continue extension works just fine

**Comment by codingdudecom** [comment]
any news on this?

**Comment by Maamar2** [comment]
still not working even with cashe delete and i uninstalled cline , i am trying using deepseek-v3 from hyberpolic withing cline but its not working , I tried google Gemini from google studio and its work , but i don't know why deepseek not working

**Comment by Ardanila** [comment]
I am experiencing the "404 status code (no body)" error. I have tried clearing the caches but it did not help. I believe this error may be related to yours.

**Comment by youwei997** [comment]
I have the same problem; my deepseek key returns a 401 error on cline, but it works on continue.

**Comment by romashkax** [comment]
> still not working even with cashe delete and i uninstalled cline , i am trying using deepseek-v3 from hyberpolic withing cline but its not working , I tried google Gemini from google studio and its work , but i don't know why deepseek not working

I had the same problem. Solution is: use base url with version in the end `https://api.hyperbolic.xyz/v1`

**Comment by Maamar2** [comment]
> > still not working even with cashe delete and i uninstalled cline , i am trying using deepseek-v3 from hyberpolic withing cline but its not working , I tried google Gemini from google studio and its work , but i don't know why deepseek not working
> 
> I had the same problem. Solution is: use base url with version in the end `https://api.hyperbolic.xyz/v1`

![image](https://github.com/user-attachments/assets/566ff380-b2f4-458b-abcd-bcbbdc50c8a9)
Nope! , not working for me

**Comment by jadsonwelder** [comment]
Hi guys, same problem "400 status code", Any solution? Tks.

**Comment by EmilyLiu03** [comment]
same here.

好奇难道不是全部兼容 OpenAI 的模型平台的 base url 不应该都是类似于 v1/ 结尾的，由使用平台自动填补 chat/completions。明明 cursor 上用的好好的，

**Comment by Maamar2** [comment]
the fix is to  set model id = deepseek-ai/DeepSeek-R1 or V3

**Comment by EmilyLiu03** [comment]
> the fix is to set model id = deepseek-ai/DeepSeek-R1 or V3

This is only supported by SiliconFlow. If you use other third-party provider, this solution won't work. For example, the model name from DS official are deepseek-chat and deepseek-reasoner. 

这个 model id = deepseek-ai/DeepSeek-R1 or V3 仅仅是硅基流动支持的，如果更换第三方服务则会报错。例如，DS 官网的 model id 是 deepseek-chat 和 deepseek-reasoner。

**Comment by EmilyLiu03** [comment]
> same here.
> 
> 好奇难道不是全部兼容 OpenAI 的模型平台的 base url 不应该都是类似于 v1/ 结尾的，由使用平台自动填补 chat/completions。明明 cursor 上用的好好的，

我的 400 报错已经解决了，怀疑是第三方服务的卡的问题。
