### ISSUE TITLE
Unable to download extension on VS Code for Mac

### ISSUE THREAD

**Issue by TheColorPlum** [cline/cline#733]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

N/A

### What happened?

Installed cline.ai on vs code, but the icon is blank and the extension page isn't loading. Seems like it didn't install properly.
<img width="420" alt="Screenshot 2024-11-13 at 11 53 13 PM" src="https://github.com/user-attachments/assets/94c5c65c-cf53-410f-abad-2db52ae2f726">

### Steps to reproduce

1. Open vs code
2. download cline extension
3. attempt to open cline extension

**Comment by DeVReV27** [comment]
Experiencing the same issue as well. Seems to have started within the past week. 

<img width="360" alt="Screenshot 2024-11-14 at 1 39 58 PM" src="https://github.com/user-attachments/assets/fe8fc82f-2030-4591-b89c-3a4903410c2f">

**Comment by DeVReV27** [comment]
Issue fixed.
<img width="360" alt="Screenshot 2024-11-14 at 1 54 51 PM" src="https://github.com/user-attachments/assets/c521ea88-3d1b-4b42-a448-b568a8560fb7">

1. Moved VS Code out of Downloads folder
2. Went to VS Marketplace and re-downloaded the extension. [https://marketplace.visualstudio.com/items?itemName=saoudrizwan.claude-dev](url)
3. Restarted VS Code - Works

Hope that helps

**Comment by TheColorPlum** [comment]
Yup that fixed it, thanks!!
