### ISSUE TITLE
Context mentions menu is not legible with light+ theme

### ISSUE THREAD

**Issue by MatthewDailey** [cline/cline#745]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet 

### What happened?

In Light+ mode, there is too little difference between text color and highlight color when selecting in the @ menu.

<img width="461" alt="Screenshot 2024-11-15 at 7 59 45 AM" src="https://github.com/user-attachments/assets/544fcafd-d8ba-4e9c-bcbf-7840638d4a54">

### Steps to reproduce

1. Set vscode color theme to `Light+`
2. Start new task
3. Type @ 

Observe that you can't read the selected item

**Comment by saoudrizwan** [comment]
Thank you for reporting!

**Comment by saoudrizwan** [comment]
Fixed in the latest v3.0.4
