### ISSUE TITLE
Cline has an issue using this function call ""list_code_definition_names"

### ISSUE THREAD

**Issue by phalexo** [cline/cline#750]
### Which API Provider are you using?

Ollama

### Which Model are you using?

qwen2.5-coder-32b-instruct

### What happened?

Cline reports that "list_code_definition_names" is not detecting definitions, and it falls back to using "read_file" which seems to work and then Cline finds the relevant definitions, as it reports.

I am looking, I guess, for a suggestion how to modify the TEMPLATE or SYSTEM for Ollama model file to add this function. Right now there is no explicit definition for "list_code_definition_names". There is no explicit definition for "read_file" either.

### Steps to reproduce

1.
2.
3.

**Comment by saoudrizwan** [comment]
You can modify cline's behavior around using these tools using Settings > Custom Instructions, your instructions here will be added directly to the system prompt
