### ISSUE TITLE
Cline Weirdly Responding in a scroll view

### ISSUE THREAD

**Issue by LousyBook-01** [cline/cline#759]
### Which API Provider are you using?

Google Gemini

### Which Model are you using?

gemini-1.5-flash-8b

### What happened?

It happens on every model sometimes, it randomly starts responding in a scroll view, and once it responds, like that you can't make it change, by telling it.

### Steps to reproduce

1. Keep talking to cline until some tasks complete
2. He responds in a scroll view

### Additional context

![image](https://github.com/user-attachments/assets/8c314b68-34ec-4523-9056-0d5a2d3f3f5f)

**Comment by saoudrizwan** [comment]
Hah that's funny, this is just a result of using a dumb model like flash 8b. If you were to use claude 3.5 sonnet this wouldn't ever happen.
