### ISSUE TITLE
o1-preview  'messages[0].role' does not support 'system' with this model. vie OpenAI Compatible 

### ISSUE THREAD

**Issue by araimbekoff** [cline/cline#760]
### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

o1-preview/o1-mini

### What happened?

400 Unsupported value: 'messages[0].role' does not support 'system' with this model.

### Steps to reproduce

400 Unsupported value: 'messages[0].role' does not support 'system' with this model.

**Comment by techadvyt** [comment]
Surely that's because the model doesn't accept Cline's complex prompts. That's a model issue rather than Cline's issue.

**Comment by araimbekoff** [comment]
> Surely that's because the model doesn't accept Cline's complex prompts. That's a model issue rather than Cline's issue.

are you sure about that?

The thing is, OpenAI has already implemented the use of the o1-preview/mini model.

Also, I tried building the plugin from source, replaced what's already been done in OpenAI, and inserted custom API URLs for this model.

This works perfectly fine for me.

Are you a plugin developer, or just a regular user?

**Comment by techadvyt** [comment]
I am just a regular user like you. Since you said you built it from source, you could make a PR and benefit the rest of the community if you want.

**Comment by saoudrizwan** [comment]
Ah yes using openai compatible to use o1 won't work because it provides a system prompt, which o1 doesn't support at the moment. I suggest using openrouter or open ai directly to work around this.

**Comment by zyzhang1130** [comment]
@saoudrizwan I suggest to make it remove system message for o1 series models, given that now o1 has more models available. Or simply use the same way the direct OpenAI one dealt with it (i.e., put the system message as the first user message)

**Comment by hardikcc** [comment]
Any solution for this? I dont think its fair to say that we can't support the one of the best available model at this time? Even Github Co-pilot supports that.
