### ISSUE TITLE
New files are not showing up in context mentions suggestions

### ISSUE THREAD

**Issue by napter** [cline/cline#772]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude

### What happened?

When a new unit is added to a project, it is not possible to add it to Cline's context using "@". The only way to get Cline to know about it is to restart the extensions host.

(As a side note, it would be useful if in the "@" context menu, there was an additional option to include any arbitrary file on the machine).

### Steps to reproduce

1. Have Cline create a new file
2. Start a new chat and try to add this file as context
3.The file does not show up in the "@" context tree

**Comment by thewbuk** [comment]
Even option to rescan files in settings would be nice as a workaround

**Comment by saoudrizwan** [comment]
Thank you for reporting!

**Comment by Kaddtechnologies** [comment]
yes need option to rescan
