### ISSUE TITLE
Cline icon desapear from primary sidebar on VScode

### ISSUE THREAD

**Issue by Productivix** [cline/cline#788]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

claude 3.5 sonnet

### What happened?

I made may be not that is expected , but the icon of Cline is not any more in the primary sidebar and so I cannot use it .

### Steps to reproduce

1.start cline
2.try to move on the left of the screen
3.I do know
then no more icon of Cline !

**Comment by saoudrizwan** [comment]
You may need to right click the sidebar to re-show Cline. The vscode panel organizer is a bit confusing!

**Comment by Productivix** [comment]
not closed  : " right click the sidebar " already tried : no solution - still no icon

**Comment by pracy1983** [comment]
same here. I can access it clicklin cntrl shift P, but it stays at the tab and I cant access settings... and still not showing at the side bar

**Comment by pandemonica** [comment]
I have the same issue. Also, sometimes the cline tab does not have the settings icon.

**Comment by adrigabzu** [comment]
The icon could have moved to the secondary sidebar. There I found it.

![Image](https://github.com/user-attachments/assets/4a6d0489-fc5d-4083-971e-35a58414fdd0)
