### ISSUE TITLE
Chore: Enable vulnerability reporting on the repo

### ISSUE THREAD

**Issue by mdp** [cline/cline#795]
### Which API Provider are you using?

OpenAI

### Which Model are you using?

N/A

### What happened?

If I want to report a security vulnerability, there's no easy way to do it on Github.

### Steps to reproduce

1. Click "Security" on the project

### Additional context

@saoudrizwan Click on https://github.com/cline/cline/security and Enable vulnerability reporting if you're open to it. Otherwise we can do email based reporting

**Comment by lloydchang** [comment]
Additionally, I suggest enabling various security features in GitHub, such as:
1. https://github.com/cline/cline/security/dependabot
2. https://github.com/cline/cline/security/security/code-scanning
3. https://docs.github.com/en/code-security/getting-started/github-security-features
4. etc.

In my fork of Cline, I enabled various security features and received vulnerability alerts via Dependabot and Code Scanning.

**Comment by saoudrizwan** [comment]
Done. Thank you.
