### ISSUE TITLE
impossible to use it 

### ISSUE THREAD

**Issue by kellspell** [cline/cline#808]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Sonnet 20241022

### What happened?

its impossible to use it , its does not finish the operations properly also the output limit is not enough to finish not even one task and also is so annoying the to stay pressing a button because it looses connection with the api , for what we are pay for the services thats not working , for God sake unfortunately this company it wont give my money back ,because at least for the service they say the provide its only lies on the midia   

### Steps to reproduce

1.
2.
3.

**Comment by saoudrizwan** [comment]
It seems like Anthropic is having server issues. I suggest using OpenRouter in the meantime.
