### ISSUE TITLE
API Request Failed

### ISSUE THREAD

**Issue by PacomeLeRouge** [cline/cline#809]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Sonnet

### What happened?

Connection error.

### Steps to reproduce

1.
2.
3.
Connection error.

### Relevant API REQUEST output

```shell
Connection error.
```

### Additional context

Connection error.

**Comment by richwood911** [comment]
I'm experiencing the exact same thing randomly. Everything has been fully functional until now.

**Comment by richwood911** [comment]
Resolved.

**Comment by richwood911** [comment]
Reoccurrence

**Comment by saoudrizwan** [comment]
It seems like Anthropic is having server issues. I suggest using OpenRouter in the meantime.
