### ISSUE TITLE
Provider returned error By Openrouter 

### ISSUE THREAD

**Issue by kiraje** [cline/cline#813]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Sonnet

### What happened?

![image](https://github.com/user-attachments/assets/d43bd988-a51a-48e7-bb83-38c8f48df8c8)
Got Provider returned error 

### Steps to reproduce

1.
2.
3.

**Comment by saoudrizwan** [comment]
Hi are you still seeing this issue? This may have happened during an outage

**Comment by saoudrizwan** [comment]
Pls feel free to re-open if you're still running into this problem

**Comment by elemental-mind** [comment]
Hmmm, running into the same issue. Have created a dozen OpenRouter API keys by now and can't get it to work.

Randomly it jumps between "Provider returned error" and a "401 unauthorized". Is there any way to see the raw requests and responses? Are they logged anywhere?

Also tried an older version (2.14) and the issue persists.

curl requests work fine, so it must be a malformed request or something?

**Comment by elemental-mind** [comment]
Ok drilled it down to a model specific error. This is solved for me now. Seems like certain models were down...

Takeaway, though: Would be really good to have some logs - or provide the raw server response in case of errors (maybe in a detail view, so it's not in plain sight, but still available if you want to dive deeper).

**Comment by Darayavaush-84** [comment]
I still have the same issue. Tried several times in the last 4-5 days. Not able to use any of the new Gemini models.

**Comment by elemental-mind** [comment]
The free and experimental models have their quota exceeded pretty quickly. Try any paid model and it should work fine.

**Comment by elemental-mind** [comment]
Try whether these models work on OpenRouter Chat for you...they probably also don't work there.

**Comment by Darayavaush-84** [comment]
But I should have a trial quota right? I am even unable to get an answer to "hello", once per day. The API works fine on Typingmind. I don't have any issue.

**Comment by elemental-mind** [comment]
Yes you have free quota, but only with the API key directly or in Google AI studio. Openrouter has a global quota across all its users, I guess.

Anyway. It's not a Cline issue.

**Comment by kiraje** [comment]
![image](https://github.com/user-attachments/assets/dd48a773-8d85-4f86-95b1-388ad8541efd)
sorry for long reply but its the problem from openrouter
you can go to their discord and ask for help

**Comment by Darayavaush-84** [comment]
Maybe I did not express myself clear enough: i have the same issue also with Cline in VSCode with API directly:

![image](https://github.com/user-attachments/assets/5726f228-4206-4d53-8c07-fc08ce0e9af7)

![image](https://github.com/user-attachments/assets/f74decc0-728c-4e75-8783-225ede2d5293)

I understand it might still not be an issue with Cline directly, but is somehow curious that people on Reddit are able to use it and I don't.

**Comment by HatsuChuwu** [comment]
> ![image](https://github.com/user-attachments/assets/dd48a773-8d85-4f86-95b1-388ad8541efd) sorry for long reply but its the problem from openrouter you can go to their discord and ask for help

所以是什么情况

**Comment by orbitrod** [comment]
same problem

**Comment by CodyM0RGAN** [comment]
I'm having the same issue trying to use openrouter.ai with Google Gemini 2.5 pro free.

**Comment by elemental-mind** [comment]
As I said earlier, not a Cline issue: OpenRouter hit their rate limit with Google - or you have hit your free rate limit for that model. 2.5 Pro free is having a lot of demand right now. 

Try setting up your API keys from AI Studio.

**Comment by CodyM0RGAN** [comment]
> As I said earlier, not a Cline issue: OpenRouter hit their rate limit with Google - or you have hit your free rate limit for that model. 2.5 Pro free is having a lot of demand right now.
> 
> Try setting up your API keys from AI Studio.

You're completely right. Sorry about that.

**Comment by eMPee584** [comment]
Ok also run into this, probably rate limited, but it would definitely be nice if error code / server response could be shown.

**Comment by ciapamusche** [comment]
same error with gemini 2.5 free. 

The big problem is that everytime you got this message you burn a free request. So yo will go out of request after few messages....

very annoying problem.

**Comment by EVCV** [comment]
im now randomly seeing this issue on my laptop

**Comment by NatsumeAoii** [comment]
per 2026, it's still happening pretty often. maybe they just didn't wan't to fix this issue.
