### ISSUE TITLE
better default provider for llama 405b (set llama 405b as default)

### ISSUE THREAD

**Issue by avianion** [cline/cline#814]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

llama 405b

### What happened?

hi.

all the llama 405b providers on openrouter aside from avian.io and fireworks are slow. and even fireworks has very high ttft.

for best coding with open source models, i think llama 405b is the best. therefore i would suggest to set llama 405b as the default model for cline, and set avian.io as the default provider.

thanks for listening

### Steps to reproduce

1. use cline
2. try to use llama 405b
3. observe that the default providers on OR are unfathomably slow

**Comment by saoudrizwan** [comment]
Thank you for the suggestion! I will look into that provider
