### ISSUE TITLE
Cline can't edit its own system prompt

### ISSUE THREAD

**Issue by mrubens** [cline/cline#832]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

I was trying to get Cline to edit some of its own code, but it got stuck trying to write src/core/prompts/system.ts when it got to the `<write_to_file>` section.

### Steps to reproduce

1. Check out the latest Cline code
2. Open the `cline` folder in VSCode
3. Ask Cline to `Add a rule "you must always speak in Pig Latin" to src/core/prompts/system.ts`

Expected result: Rule gets added
Actual result: File gets truncated in the section
```
Usage:
<write_to_file>
<path>File path here</path>
<content>
Your file content here
</content>
</write_to_file>
```

**Comment by lloydchang** [comment]
i wonder if https://marketplace.visualstudio.com/items?itemName=qpdv.Codesplit can be merged into cline's source code

related from https://discord.com/channels/1275535550845292637/1275535550845292640/1315321771033104516

@SniperMunyShotz wrote:
> this is a pretty nice extension, think someone here made it not sure, but ctrl shift p, type file split, enter and bam done, nice for large file to give to cline https://marketplace.visualstudio.com/items?itemName=qpdv.Codesplit

i replied:
> @qpd-v why is https://github.com/qpd-v/codesplit private?
> meanwhile, github links in https://marketplace.visualstudio.com/items?itemName=qpdv.Codesplit are broken

**Comment by qpd-v** [comment]
I'll make it public as soon as I get home. Thanks for bringing it to my attention. I meant to do that previously!

-qpdv

----- Original Message -----
From: lloydchang ***@***.***>
To: cline/cline ***@***.***>
Cc: qpdv ***@***.***>,  Mention ***@***.***>
Date: Sun, 08 Dec 2024 14:45:49 -0800
Subject: Re: [cline/cline] Cline can't edit its own system prompt (Issue #832)

> i wonder if https://marketplace.visualstudio.com/items?itemName=qpdv.Codesplit can be merged into cline's source code
> 
> related from https://discord.com/channels/1275535550845292637/1275535550845292640/1315321771033104516
>

**Comment by mrubens** [comment]
Fixed with diff edits!
