### ISSUE TITLE
Claude 3.5 Sonnet API issues

### ISSUE THREAD

**Issue by whoAmI-cslim** [cline/cline#875]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

Today for some reason, any Claude 3.5 Sonnet requests are getting the following errors:

Error
Unexpected API Response: The language model did not provide any assistant messages. This may indicate an issue with the API or the model's output.

Cline is having trouble...
This may indicate a failure in his thought process or inability to use a tool properly, which can be mitigated with some user guidance (e.g. "Try breaking down the task into smaller steps").

### Steps to reproduce

1. Start a project
2. Ensure OpenRouter is selected
3. Ensure Claude 3.5 Sonnet is selected

### Relevant API REQUEST output

```shell
Error
Unexpected API Response: The language model did not provide any assistant messages. This may indicate an issue with the API or the model's output.


Cline is having trouble...
This may indicate a failure in his thought process or inability to use a tool properly, which can be mitigated with some user guidance (e.g. "Try breaking down the task into smaller steps").
```

### Additional context

This is something new. When I use Haiku, it's fine.

**Comment by Aldelaigan** [comment]
I keep getting "API request failed: connection error". I tried using different environments with new projects

**Comment by jrosocha** [comment]
Similar

`[ERROR] You did not use a tool in your previous response! Please retry with a tool use.

# Reminder: Instructions for Tool Use

Tool uses are formatted using XML-style tags. The tool name is enclosed in opening and closing tags, and each parameter is similarly enclosed within its own set of tags. Here's the structure:

<tool_name>
<parameter1_name>value1</parameter1_name>
<parameter2_name>value2</parameter2_name>
...
</tool_name>

For example:

<attempt_completion>
<result>
I have completed the task...
</result>
</attempt_completion>

Always adhere to this format for all tool uses to ensure proper parsing and execution.`

**Comment by weekapang** [comment]
i am having the same error as well, just started this morning

**Comment by acrilique** [comment]
Meanwhile, [Anthropic's status page](https://status.anthropic.com/) shows "All systems operational". Doesn't make much sense to me.

**Comment by dfeirstein** [comment]
I am also having this issue with Claude 3.5 Sonnet thru OpenRouter and I tried direct through Anthropic

**Comment by weekapang** [comment]
> I found using the 3.5:beta still works.
appreciate it, i found claude-3.5-sonnet-20240620:beta is the version I can get working

**Comment by cortes-ventures** [comment]
Getting the same error here only when it tries to read files.

**Comment by gabrielgrant** [comment]
Is there a way to see the full request/response details and raw error?

I'm just seeing `API Request Failed - Connection error` in the chat:
![image](https://github.com/user-attachments/assets/35444148-2d98-47c7-b1b5-29bc1fac5bd1)

I'd expect the debug info for these errors to be in the VS Code extension output, but I'm seeing very little in there:

![image](https://github.com/user-attachments/assets/a5b04e51-d7c8-4e03-9d9c-db02d3a44b56)

**Comment by younes-io** [comment]
same here

**Comment by whoAmI-cslim** [comment]
It is now working perfectly for me today. Thanks for all you guys do!

**Comment by Abdoxh9r** [comment]
still, having this issue for 2 days

**Comment by zzt108** [comment]
I had similar issues several days ago with OpenRouter API, then switched to OpenAI API and the issue went away. In my opinion this is a problem with the API server, not with cline.

**Comment by acrilique** [comment]
I also agree, this might not be a problem with Cline. It seems to be a problem with the API server, but only related to a specific model or a set of models, probably due to great demand during specific periods of time. 
**Advice** for anyone facing this:
`Try to switch to another model (or a different version of the same model, if that applies). If that model also has the same problem or if you don't want to use that model, try to switch to a different API (be it OpenRouter's, Anthropic's, OpenAI's...). Then, if that also fails (or if you can't/won't pay for another API), the only thing you can do is wait. Truth is you probably won't get the same error if you try again later.`

**Comment by saoudrizwan** [comment]
Is it okay for me to close this issue? There was an openrouter/anthropic outage earlier but it seems to be resolved now.

**Comment by tluyben** [comment]
This is an issue with openrouter; when this happened, Anthropic their own API was working perfectly fine (I switch to it when openrouter is not working).

**Comment by omole1** [comment]
Im having a similar issue, did any person manage to fix it ?

**Comment by orbitrod** [comment]
having same problem

**Comment by bitflower** [comment]
I have this since today. Worked fine in the morning, now it's broken.

**Comment by ZhuoQian111** [comment]
@saoudrizwan you're issue closing machine🥲

**Comment by MarkChrisE2091** [comment]
Same issue with Claude Code on VSCode. 
Why this issue is closed? Any fix?
