### ISSUE TITLE
All tasks result in this error: The language model did not provide any assistant messages.

### ISSUE THREAD

**Issue by byjlw** [cline/cline#876]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Claude Sonnet 3.5

### What happened?

All of a sudden every task results in this error. Everything was working fine when I went to bed last night. Started getting this first time this morning. 

`Unexpected API Response: The language model did not provide any assistant messages. This may indicate an issue with the API or the model's output.`

### Steps to reproduce

Open up a project in VS Code
Start a new task and ask for changes to a file

**Comment by acrilique** [comment]
Same as #875

**Comment by Abdoxh9r** [comment]
not even asking for changes, just say hey is producing this issue for me

**Comment by saoudrizwan** [comment]
Seems like this was due to an openrouter/anthropic outage–can you please check if you're still having issues?

**Comment by mmintel** [comment]
@saoudrizwan I got that problem today as well and after about 30mins it went away

**Comment by remster88** [comment]
Got this issue since yesterday.

**Comment by robertalers** [comment]
Same issue since today!

**Comment by SebastianNachtigall** [comment]
I also have this issue as of now. was working earlier today. Anthropic does seem to work https://status.anthropic.com/ also I cannot see any indication on my openrouter page..

**Comment by Sama486** [comment]
Same issue with DeepSeek reasoner.

**Comment by skoenman** [comment]
ok so its not just me... also getting issue with deepseek resoner

**Comment by zimudehub** [comment]
同样的问题

**Comment by rbd340** [comment]
I have the same issue with deepseek, first call is OK, all calls after are not

**Comment by yougikou** [comment]
Why is this case closed?

**Comment by lukasj783** [comment]
Unexpected API Response: The language model did not provide any assistant messages. This may indicate an issue with the API or the model's output. i get this error when i use deepseek api via cline and roo code

**Comment by orbitrod** [comment]
same problem

**Comment by obitoquilt** [comment]
same problem

**Comment by truebit** [comment]
same problem for claude-3.7

**Comment by veyselsahin** [comment]
changing reasoning effort from high to medium fixed my issue in kilocode as it was the same error message.

**Comment by crizCraig** [comment]
Just got this with Sonnet-4 thinking on polychat.co and it went away on its own after a few minutes.

**Comment by aybbberrada** [comment]
I'm getting this with openrouter: gpt-oss-120b

**Comment by rvabrilot** [comment]
also ocurring with gpt-oss-20b

**Comment by Du4lity5151** [comment]
> also ocurring with gpt-oss-20b

Same here. I'm using llama.cpp through OpenAI compatible server using the same model and it appears to show "error: the request exceeds the available context size. try increasing the context size or enable context shift" in the llama.cpp console window every time I attempt to ask it to do something. Tried lowering the context window size below what I set for llama.cpp to no avail.

**Comment by SEVENID** [comment]
Same with gpt-oss-20b on ollama. Any other model works fine.

**Comment by FrankLaterza** [comment]
can we reopen this?

**Comment by ZhuoQian111** [comment]
Same issue for Deepseek and Qwen3-coder, I have regenerated an new API key but it still didn't work

**Comment by tungnk41** [comment]
gpt -oss-120b and 20b have the same problem, I think because it's the new model, dev team should fix it

**Comment by silwerdivan** [comment]
Switched to Roo Code. Hopefully this will get resolved. :crossed_fingers:

Mmm, got this with Roo Code as well. Seems intermittent. :thinking:

I'm using Gemini 2.5 Pro.

There's an open issue.
https://github.com/RooCodeInc/Roo-Code/issues/6999

**Comment by outbound** [comment]
Same here

**Comment by himitu-da** [comment]
Gemini 2.5 Pro

**Comment by CarcajadaArtificial** [comment]
@saoudrizwan Please reopen this issue, it's clearly not solved.

**Comment by JoshuaDietz** [comment]
I am also experiencing this issue since a few days when using `claude-code:claude-sonnet-4-20250514`. When using claude code myself as a replacement for cline, there are no problems at all.

**Comment by outbound** [comment]
I experience this issue a ton when going through OpenRouter. Going via
Anthropic directly, or Claude Code, I haven't experienced it. Yet.

**Comment by Nero10578** [comment]
Roo code is absolutely unusable now, keeps getting this error for me too.

**Comment by barjuandavis** [comment]
Folks, I don't think this problem is a Cline/Roo problem -- I believe it's more relevant to put this problem on OpenRouter (not sure where to put the issue though). The issue happens when I tried using gpt-oss-120b, but resolved when using kimi-k2.

**Comment by AlexAtmtit** [comment]
Experiencing the same issue with various providers (AI Studio, Nvidia) what happened?

**Comment by Kos-M** [comment]
Same here..

**Comment by sgrodnik** [comment]
Gemini 2.5 Pro. If I switch to Gemini 2.5 Flash, the problem will occur 100 times less often. Today, 99% of requests end up on this. Yesterday, it was 20%. And I believe the problem is not in the quota.

<img width="222" alt="Image" src="https://github.com/user-attachments/assets/b2848bbc-e97b-488d-b367-454670f0ba53" />

**Comment by KanTakahiro** [comment]
It is 2025.08.20 1:30 UTC, I updated RooCode to 3.25.18, Kilo Code to 4.82.1. Then this issue was solved.
BTW I am using Qwen/Qwen3-Coder-480B-A35B-Instruct on DeepInfra.

**Comment by fishingpvalues** [comment]
I receive this error all the time with different providers.

**Comment by ShenJason99629** [comment]
same problem in gemini2.5pro

**Comment by NischalGautam8** [comment]
same issue with gemini 2.5 pro

**Comment by mercmobily** [comment]
This issue shouldn't be closed. I am getting this with deepseek. I hit retry a couple of times, and it worked eventually

**Comment by mercmobily** [comment]
This is what happened twice. The third time it worked:


>> Thinking First, I need to respond to GitHub issue #2502 for the repository. According to the user's custom instructions, I need to: 1. Fetch the issue details using the gh command 2. Analyse the issue thoroughly 3. Check the code to understand the problem 4. Write a response in British English 5. Place the response in the responses/2502.md file 6. Include related issues and exact duplicates 7. Not use markdown headers, use bold for headings if needed 8. Not make any changes to the repository Let me start by fetching the issue details using the gh command. <thinking> I need to use the execute_command tool to run the gh command to fetch issue #2502. The gh command is GitHub's CLI tool, so I should be able to use it to get the issue details. The command would be something like: `gh issue view 2502 ` I should also check if there are any comments on the issue, so I might need to get the full discussion. </thinking> <execute_command> <command>gh issue view 2502 --</command> <requires_approval>false</requires_approval> <task_progress> - [ ] Fetch issue #2502 details - [ ] Analyse the issue and related code - [ ] Check for related/duplicate issues - [ ] Write response in responses/2502.md </task_progress> </execute_command>

>> Unexpected API Response: The language model did not provide any assistant messages. This may indicate an issue with the API or the model's output.


The process stopped twice in the exact same spot. I have custom_instructions.md set

**Comment by ShenJason99629** [comment]
it needs to repeat retry button again and again and probably not works in the end

> This issue shouldn't be closed. I am getting this with deepseek. I hit retry a couple of times, and it worked eventually
>

**Comment by lesydat** [comment]
same issue with gpt-oss-120b

**Comment by alex-erygin** [comment]
same issue with x-ai/grok-code-fast-1

**Comment by irreg** [comment]
@lesydat 
Regarding gpt-oss, this will likely improve it.
[native_tool_call_adapter](https://github.com/irreg/native_tool_call_adapter)

**Comment by MarkChrisE2091** [comment]
Same issue with Claude Code on VSCode

**Comment by MarkChrisE2091** [comment]
Why this issue is closed? Any fix?

**Comment by lesydat** [comment]
> [@lesydat](https://github.com/lesydat) Regarding gpt-oss, this will likely improve it. [native_tool_call_adapter](https://github.com/irreg/native_tool_call_adapter)

look like this tool doesn't support API Key

**Comment by irreg** [comment]
> > [@lesydat](https://github.com/lesydat) Regarding gpt-oss, this will likely improve it. [native_tool_call_adapter](https://github.com/irreg/native_tool_call_adapter)
> 
> look like this tool doesn't support API Key

This tool passes parameters other than the tool calling relationship directly from cline, so it should work if you set the API key on the cline side.
