### ISSUE TITLE
[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:streamGenerateContent?alt=sse: Invalid URL protocol: the URL must start with `http:` or `https:`.

### ISSUE THREAD

**Issue by muqiann2022** [cline/cline#898]
### Which API Provider are you using?

Google Gemini

### Which Model are you using?

Gemini

### What happened?

[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:streamGenerateContent?alt=sse: Invalid URL protocol: the URL must start with `http:` or `https:`.

### Steps to reproduce

1.setting up the proxy as a socks://...
2.type in any base url
3.post a request to LLMs

### Additional context

So I changed the proxy into http, the problem didn't show up.

**Comment by LongwayCHOW** [comment]
changed into http，show error again 😂：[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:streamGenerateContent?alt=sse: fetch failed

**Comment by hnsxxscyx** [comment]
Add 	"http.proxy": "http://127.0.0.1:7890", into your config.
cannot use sock5://
