### ISSUE TITLE
Cline零代码开发MCP Server完整视频

### ISSUE THREAD

**Issue by win4r** [cline/cline#912]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

https://youtu.be/7BFMY0yuRAY

### What happened?

https://youtu.be/7BFMY0yuRAY

### Steps to reproduce

1.
2.
3.
https://youtu.be/7BFMY0yuRAY

### Relevant API REQUEST output

```shell
https://youtu.be/7BFMY0yuRAY
```

### Additional context

https://youtu.be/7BFMY0yuRAY

**Comment by AlexJ-StL** [comment]
@win4r... Dude this isn't a bug its f-ing spam. There are two posts for the same thing #911 & #912.
