### ISSUE TITLE
to many bugs

### ISSUE THREAD

**Issue by bob10042** [cline/cline#914]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

dosnt matter 

### What happened?

cline continually comes up with rate limits which are not true and consistantly trunactes code destroying file in the process 429 rate limits which are not real think its really broken. to many issues now.

### Steps to reproduce

1.
2.
3.

**Comment by davefellows** [comment]
I've been using Cline with OpenRouter claude-3.5-sonnet and haven't had any issues at all. Might pay to provide further details what exactly you're using/doing.

**Comment by saoudrizwan** [comment]
I hope your experience with v3 is better with the new diff editing.

**Comment by bob10042** [comment]
Yep massive improvement still issues with editing files, alignment and certain tool use Another really annoying problem when you get the 429 error in the middle of the work you are doing it would it would be great if you just continue without explanation or spending a lot of time backing stuff up. Still beats anything out there that you have to pay for, infact I would say there’s no competition. One more thing sometimes it gets into repetitive loops trying to fix stuff. Overall great job and as I said before this is one tool I would definitely pay for. Wouldn’t it be great to accomplish self reflection in the code space???Anyway happy new year 🥳 Regards Bob.Sent from my iPhoneOn 26 Dec 2024, at 00:12, Saoud Rizwan ***@***.***> wrote:﻿
I hope your experience with v3 is better with the new diff editing.
