### ISSUE TITLE
UI Bug: Accessibility of text in light theme

### ISSUE THREAD

**Issue by tusharmath** [cline/cline#915]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Claude 3.5

### What happened?

The text is unreadable in light theme.

<img width="554" alt="Screenshot 2024-12-14 at 9 30 07 AM" src="https://github.com/user-attachments/assets/ab09a9b2-960d-49e0-a4ad-c09b5cb021ad" />

### Steps to reproduce

1. Use VS Code in Light+ Theme
2. Click on Cline Extension
3. Type `@` and wait for auto-complete

**Comment by Diem0n** [comment]
I would like to contribute and fix this

**Comment by saoudrizwan** [comment]
Fixed by https://github.com/cline/cline/pull/942
