### ISSUE TITLE
mandatory API Key on OpenAI Compatible endpoint

### ISSUE THREAD

**Issue by Xyz00777** [cline/cline#929]
### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

unrelevant

### What happened?

i want to use the openai compatible endpoint without an api key because its not provided by every programm eg litellm.

### Steps to reproduce

1. want to use litellm as llm endpoint
2. type in all fields without api key because its not available for it
3. cant save setting because api key field got marked as mandatory.....

**Comment by saoudrizwan** [comment]
You can use a dummy value like 'noop' and it should work!
