### ISSUE TITLE
Anthropic Provider is hallucinating

### ISSUE THREAD

**Issue by alpsla** [cline/cline#930]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

claude-3-5-sonnet-20241022

### What happened?

Any prompt responses are false and cause more damage than I had. I contacted to the Anthropic and they had an outage a couple of days before for 3 days. They fixed that and probably pushed a new version. Could you update the model in your settings, and even better make an option for users to pick version themselves? Anthropic support suggested eiver to try 1 version before or a Beta version, but you gave me no chances to do that 

### Steps to reproduce

1.
2.
3.

**Comment by saoudrizwan** [comment]
Please see https://github.com/cline/cline/pull/844#issuecomment-2562048273
