### ISSUE TITLE
Error while using Cline with Gemini Flash 2.0

### ISSUE THREAD

**Issue by ARYANGS** [cline/cline#931]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

gemini flash 2.0

### What happened?

whenever i enter the message, it loads for a few seconds and then shows the "API request failed" message followed by "Provider returned error"

### Steps to reproduce

1. openrouter api with gemini flash 2.0
2. run message
3. "Provider returned error"

### Relevant API REQUEST output

```shell
API Request Failed: Provider returned error
```

### Additional context

![Screenshot 2024-12-16 234736](https://github.com/user-attachments/assets/676596e1-e6e7-4546-a882-276e10d0499f)

**Comment by Khalil-Zaman** [comment]
I think this is to do with OpenRouter, as Flash 2.0 now works on Open Router, which now also works on Cline. But 1206 is still throwing an error on OpenRouter. Seems similar to this https://github.com/cline/cline/issues/813

**Comment by ARYANGS** [comment]
> I think this is to do with OpenRouter, as Flash 2.0 now works on Open Router, which now also works on Cline. But 1206 is still throwing an error on OpenRouter as well as Cline. Seems similar to this #813

**Comment by ARYANGS** [comment]
I'm still getting this error for both Flashh 2.0 and exp1206 on cline. Gemini 2 is too busy and hence unavailable. I spent considerable time trying to fix this as my account activity page clearly showed I was using Gemini 2 tokens, yet I consistently received the error.  However, I tried llama and open router responded immediately and the corresponding tokens for llama were displayed on my activity page. I waited a few hours and got responses on flash 2.0, but the connection soon returned the same error message. I gave up and went back to accessing Gemini 2 Flash on studio[.]google[.]ai  which works great and you can set the tools and temperatures as needed. I'm still looking for a fix tho as the cline's self editing tool is very helpful

**Comment by m-check1B** [comment]
Gemini 2.0 broken today too via Open Router, and definitely not working at all via Google provider

**Comment by mdp** [comment]
Looks related to #962

**Comment by fridaystreet** [comment]
see my answer here https://github.com/cline/cline/issues/962#issuecomment-2557895247

you need a 'paid' google key, it won't work through openrouter

**Comment by saoudrizwan** [comment]
Thank you @fridaystreet
