### ISSUE TITLE
Caching seems not showing with OpenRouter

### ISSUE THREAD

**Issue by michelescippa** [cline/cline#935]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

claude 3.5 sonnet

### What happened?

When I use OpenRouter API, chaching data is not shown on the UI.
Anyway, in the billing page of OpenRouter it seems working.
With Direct API it shows correctly.
Version 2.2.2

### Steps to reproduce

1. In settings choose OpenRouter and Claude 3.5 Sonnet
2. Start typing
3. No info about caching is shown

**Comment by dannykorpan** [comment]
Same issue here, using cline 3.0.3.

**Comment by ajaysourcedigital** [comment]
same issue with me. Using latest cline

**Comment by saoudrizwan** [comment]
OpenRouter does not report prompt caching in their API the way Anthropic does. I will add it in the extension as soon as it's available!
