### ISSUE TITLE
API Request failing with "[GoogleGenerativeAI Error]: Error fetching from..."

### ISSUE THREAD

**Issue by telegraph-pole-head** [cline/cline#936]
### Which API Provider are you using?

Google Gemini

### Which Model are you using?

Gemini 2.0 Flash Experimental

### What happened?

Can't use gemini, getting error:

```json
{
  "error": {
    "message": "[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:streamGenerateContent?alt=sse: [400 ] * GenerateContentRequest.tools[0].function_declarations[0].parameters.required[0]: property is not defined\n"
  },
  "provider": "google"
}
```

### Steps to reproduce

1. use api key from google ai studio
2. just chat
3.

### Relevant API REQUEST output

```shell
{
  "error": {
    "message": "[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:streamGenerateContent?alt=sse: [400 ] * GenerateContentRequest.tools[0].function_declarations[0].parameters.required[0]: property is not defined\n"
  },
  "provider": "google"
}
```

**Comment by Huge** [comment]
hey @saoudrizwan , seems there is no `cline version` field in the [bug form](https://github.com/cline/cline/issues/new?assignees=&labels=bug&projects=&template=bug_report.yml), perhaps worth adding to make debugging process less confusing.

**Comment by nikolaidk** [comment]
Had same issue. I created a key in google ai studio and added it to https://openrouter.ai/settings/integrations then everything started working  :)

**Comment by xiangnanscu** [comment]
same error:
![image](https://github.com/user-attachments/assets/1ba58996-e130-43e9-9eb8-4eb04758d42c)

**Comment by saoudrizwan** [comment]
@Huge just added, good idea!

**Comment by saoudrizwan** [comment]
We'll need to look at the response and show a more user friendly error message.

**Comment by saoudrizwan** [comment]
Closing as duplicate of https://github.com/cline/cline/issues/937
