### ISSUE TITLE
Gemini 2.0 flash failed api

### ISSUE THREAD

**Issue by Car-Role** [cline/cline#959]
### Which API Provider are you using?

Google Gemini

### Which Model are you using?

Gemini 2.0 flash 

### What happened?

I am using gemini 2.0 flash. I have to "retry" the failed API repeatedly. Would be great if this automatically attempted to retry a few times. with a set time-out

### Steps to reproduce

1. use gemini 2.0 flash
2. run a larger task
3.api request failed

### Relevant API REQUEST output

```shell
[GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:streamGenerateContent?alt=sse: [500 Internal Server Error] Internal error encountered.
```

**Comment by mdp** [comment]
Maybe related to #962

**Comment by saoudrizwan** [comment]
^ Agree related to #962. It's out of the extension's scope to implement an automatic retry mechanism and recommend using a more reliable API.

**Comment by shamreenhassan** [comment]
try using python -m streamlit run yourapp.py
