### ISSUE TITLE
API Request Failed: 429 status code (no body)

### ISSUE THREAD

**Issue by Steve-Sexton** [cline/cline#962]
### Which API Provider are you using?

Google Gemini

### Which Model are you using?

gemini-2.0-flash-exp

### What happened?

While using cline v3.0.1 the API fail every 5 to 10 prompts with error "API Request Failed: 429 status code (no body)"

### Steps to reproduce

1. Use cline v3.0.1 continuously
2.
3.

### Relevant API REQUEST output

```shell
[write_to_file for 'memlog/changelog.md'] Result:

The content was successfully saved to memlog/changelog.md.

Here is the full, updated content of the file:

<final_file_content path="memlog/changelog.md">
# Changelog

Initial commit.
- Reviewed .clinerules file.
- Fixed build error in src/App.tsx.

</final_file_content>

Please note: If you need to make further changes to this file, use this final_file_content as the new reference for your SEARCH/REPLACE operations, as it is now the current state of the file (including any auto-formatting done by the system).



<environment_details>
# VSCode Visible Files
memlog/changelog.md

# VSCode Open Tabs
memlog/url_debug_checklist.md
memlog/tasks.log
memlog/stability_checklist.md
src/App.tsx
memlog/changelog.md
</environment_details>
```

**Comment by RaySinner** [comment]
Exponential backoff and retry logic have been around for a number of years. These basic techniques for handling resource exhaustion or API unavailability also apply to LLMs. When a generative AI application’s calls floods a model’s API, or when an excessive amount of queries overloads a system, backoff and retry logic in the code can help. The waiting time increases exponentially with each retry until the overloaded system recovers.

@saoudrizwan A solution to this problem could be an additional general setting on all connectors that allows you to set the wait time between each request, both system and user. Please add this setting today, otherwise so many people are suffering))

**Comment by RaySinner** [comment]
I don’t know how long to wait for changes, so I rebuilt the solution. Adding wait as a global parameter worked quite well, now it’s comfortable to use and you can spend all 1500 requests per day.

![image](https://github.com/user-attachments/assets/ca711696-12ca-4ad3-863a-87d1c31a6473)

**Comment by fridaystreet** [comment]
are you using a free gemini api key? You need to create the api key in a google project that has a valid billing account attached to it. (ie it has a credit card on it). You won't get billed for gem 2.0 use (yet), but your api key will show up in ai studio as 'paid' and you won't get the free tier rate limits

1206-exp and thinking do still seem to have heavy rate limits regardless, but once I had this setup, vaniall 2.0-flash-exp works. It does get a bit slow when the US wake up, but very rarely any 429, in fact I don't think I've had one

**Comment by RaySinner** [comment]
Perhaps this will indeed be the solution. However, a simple delay is definitely not a solution, it’s a crutch. If you read the article, the real solution would be to add a dynamic delay using the algorithm:
The first time receiving 429 there is a delay of 5 seconds, the second time - ten. If the request passes, then we reduce the delay by 5 seconds, again it passes by another 5 seconds. You also need to make a button for setting up an automatic request repeat in case of an error if the delay is turned on

**Comment by fridaystreet** [comment]
@RaySinner do you know when this delay setting might make it into the release? Also will it be a global setting you can use on any provider?

**Comment by RaySinner** [comment]
> @RaySinner do you know when this delay setting might make it into the release? Also will it be a global setting you can use on any provider?

I came to the conclusion that a simple delay is not a complete solution, and you need to write an algorithm that will allow you to dynamically move the delay window depending on the frequency of receiving error 429, so I hope the author of cline will find a more elegant solution. If you just want a delay, then you can already assemble it from my git. Now I’ll think about it and within 2 hours I’ll make an automatic confirmation of the continuation of spam requests coupled with a delay

**Comment by fridaystreet** [comment]
No worries thanks for the info

**Comment by hlsitechio** [comment]
hi, is there a parameter to change the endpoint server URL inside of Cline settings to test if its maybe the endpoints server that have a problem related to the model we use ? there is a lot of updates made by Google .. so I want to see if there a possibility to test other endpoint somewhere...

**Comment by RaySinner** [comment]
in general, I settled on spam mode + a delay of each message by 5 seconds, a quite useful crutch and you can spend all 1500 free requests per day from each key.

![image](https://github.com/user-attachments/assets/fe31c8b2-db56-4616-86b3-aae8f8adf9cc)
![image](https://github.com/user-attachments/assets/314eaf9a-aeaf-4e4b-a0f9-73476c855aad)
![image](https://github.com/user-attachments/assets/90343519-834f-4b7b-a813-192835c3247d)


I hope the author of cline will do something similar in the future.

**Comment by fridaystreet** [comment]
Why don't you just do a PR to the main Cline branch? . I'm sure they'll consider it. Much less work for them to do too if they don't need to reinvent your wheel

**Comment by RaySinner** [comment]
Because this is not a solution to the problem, but a crutch for those who need to use it now. Neither the architecture is consistent nor the approach itself is correct. Just anyone who encounters this error and if it bothers them can download this solution.

**Comment by ndbroadbent** [comment]
This is great, I really need this request delay feature as well because the rate limits are so annoying. I still haven't heard back from sales at Anthropic, and I'm worried that it's going to cost a ton of money to increase the rate limit. (Although I'm very happy to pay for all the API requests, so I don't know what's the problem.)

Anyway, this would be great so I can leave it running in the background and come back later.

**Comment by saoudrizwan** [comment]
> Because this is not a solution to the problem, but a crutch for those who need to use it now. Neither the architecture is consistent nor the approach itself is correct. Just anyone who encounters this error and if it bothers them can download this solution.

Thank you @RaySinner for being considerate about what should be merged to main. It would be irresponsible of me to the API providers if I added this solution officially.

**Comment by illwheat** [comment]
> are you using a free gemini api key? You need to create the api key in a google project that has a valid billing account attached to it. (ie it has a credit card on it). You won't get billed for gem 2.0 use (yet), but your api key will show up in ai studio as 'paid' and you won't get the free tier rate limits
> 
> 1206-exp and thinking do still seem to have heavy rate limits regardless, but once I had this setup, vanilla 2.0-flash-exp works. It does get a bit slow when the US wake up, but very rarely any 429, in fact I don't think I've had one

You are the boss.
