### ISSUE TITLE
A suspicious plugin BIPRO (prev. Cline)

### ISSUE THREAD

**Issue by hongbo-miao** [cline/cline#966]
I saw a plugin called BIPRO (prev. Cline) which is kind of suspicious. 🤔
Anyway, just let you know.
https://marketplace.visualstudio.com/items?itemName=bipro.bipro-dev

(Please feel free to close this ticket)

**Comment by Huge** [comment]
github link there is super-sus, so I reported it via email( linked o the marketplace)

**Comment by saoudrizwan** [comment]
I've opened an issue for the author to change the icon. https://github.com/bipash25/cline-with_more_models/issues/1
