### ISSUE TITLE
MCP hub not available error

### ISSUE THREAD

**Issue by SkyfallWasTaken** [cline/cline#969]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

When sending a message to Cline chat, I got a "API Streaming failed: MCP hub not available" error.

### Steps to reproduce

1. Install Cline for VS Code w/ fresh settings
2. Send a message to Cline chat
3. Get a "API Streaming failed: MCP hub not available" error.

### Additional context

Using Windows 11 w/ a WSL project open.

**Comment by tpdph** [comment]
Same here from last update, using Gemini flash 2.0 exp

**Comment by ctwhome** [comment]
same here, Cline stopped working

**Comment by cheehab051** [comment]
same here

**Comment by saoudrizwan** [comment]
I believe restarting VSCode should fix this issue. Someone in the discord mentioned they were using windsurf with cline, updated to the latest and saw this issue, but after quitting and restarting the issue was resolved. Please let me know if this helps

**Comment by SkyfallWasTaken** [comment]
Yeah that worked for me, thanks!

**Comment by Baroni7777** [comment]
Aqui para mim o erro ocorreu quando cliquei com botão direito no windows explorer e fui em abrir com code. Acho que deve acontecer o mesmo quando chama por terminal com .code, ao invez de abrir o programa diretamente e abrir a pasta do projeto.

**Comment by tpdph** [comment]
If you move it to the pannel or secondary position it seems to reset as well without having to fully restart

**Comment by liucclear** [comment]
> If you move it to the pannel or secondary position it seems to reset as well without having to fully restart

move it and fail again

**Comment by agileandy** [comment]
Trying to run any model through Ollama is failing with a 404.

Ollama is serving fine to the cli, and browser.

**Comment by ranedisk** [comment]
have the same issue,  i managed to partially fix it w/ the comment above  to "move the pannel or secondary position" then nothing happend, restarted it and it then worked but only the deepseek-chat, the reasoner does not work anymore , same issue on another desktop. Still getting this error " API streaming Failed Cannot read properties of undefined (reading 'type')]"  with reasoner. Spins for 10m+ and finally get the message above.

May not be related but i do see deepseek has it's own exetension now for VS, wondering if maybe some modules may have broken.
I did see another post somewhere having to modify something ( lost that link)

**Comment by zealllot** [comment]
Restarting worked.

**Comment by chisgit** [comment]
What was this closed, I tired 3.2 still getting the same error: MCP Hub error.

**Comment by Hamza5** [comment]
This problem started when I moved Cline from the primary sidebar to the secondary one! (The same sidebar that has Copilot Chat). The solution was to restore Cline to the primary sidebar and then restart VS Code.

This is really strange because the choice of the sidebar is a UX matter and should not affect the function of Cline.

**Comment by Kaddtechnologies** [comment]
Came here to post the same. Why on earth would sidebar location matter? I moved cline to secondary so that I can use roo in the primary and then cline tells me that MCP hub not available. 

Fix this guys. We should be able to place cline anywhere in the ide and it still should work the same

**Comment by johan456789** [comment]
Ok I just encountered this issue and restarting did fix it for me. My cline is in the secondary secondary sidebar still.

**Comment by KianaMei** [comment]
That's true. I also solved it by restarting.

**Comment by hakzarov** [comment]
same, if it's reproducible with moving chat to other side, it'd be great to cover it with a test and fix

**Comment by pijim** [comment]
Still a problem.  Just for it using 3.11.4 roo-code and vscode 1.98.2 on windows

**Comment by mrpastewart** [comment]
Same here. Experienced this last night on Ubuntu 24.04. Restarting did fix the issue.
