### ISSUE TITLE
@URL failed

### ISSUE THREAD

**Issue by GuoAccount** [cline/cline#971]
### Which API Provider are you using?

Ollama

### Which Model are you using?

qwen2.5-coder

### What happened?

in China's network environment can not get third-party web content, should be one of your middle service depends on your existing network environment; cursor is not the above problem, you can see that this point can be solved!

### Steps to reproduce

Switching to a Chinese network reproduces it

Screenshot of error:
![图片](https://github.com/user-attachments/assets/8d122e8d-5104-4082-8e66-980e2ee57931)
![图片](https://github.com/user-attachments/assets/879acbf6-b803-4d8c-b8ce-d80e39e9bff4)

**Comment by saoudrizwan** [comment]
Very interesting... so it seems when you use a URL in cursor they get the content serverside. Cline on the other hand does this locally by launching a headless browser on your computer to retrieve the content.
