### ISSUE TITLE
 Array buffer allocation failed

### ISSUE THREAD

**Issue by Steve-Sexton** [cline/cline#972]
### Which API Provider are you using?

OpenAI Compatible

### Which Model are you using?

gemini-2.0-flash-exp

### What happened?

Runtime Status
Activation
Activated by onView:claude-dev.SidebarProvider event: 1ms

Uncaught Errors (62)
 Array buffer allocation failed
 Array buffer allocation failed
 Array buffer allocation failed
 Array buffer allocation failed
 Array buffer allocation failed
 ...

### Steps to reproduce

1. Open extensions tab and click on cline
2. go to FEATURES - Runtime Status
3. view the errors to the right

### Additional context

Installation
Identifier
saoudrizwan.claude-dev
Version
3.0.3
Last Updated
2024-12-20, 08:09:30

**Comment by saoudrizwan** [comment]
This seems like an API error and not something I can address client side. Please feel free to re-open if you think that's not the case
