### ISSUE TITLE
Cline plugin incompatible with non-official Claude API

### ISSUE THREAD

**Issue by famadeuser** [cline/cline#974]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

Claude 3.5 Sonnet

### What happened?

I encountered an issue when using the Cline plugin in VSCode with a non-official Claude API. The plugin fails to send a request and returns a 400 Bad Request error. This issue occurs specifically with the Claude API, while other APIs (like GPT) work without any problems.

### What I expected to happen:
The plugin should successfully send the request to the Claude API endpoint and receive a valid response.

### What actually happened:
Instead of processing the request, the plugin returned a 400 Bad Request error.

I am using a non-official Claude API with a standard endpoint and key. The issue seems related to the plugin's compatibility with this API format. While the non-official Claude API works in other scenarios, the error occurs only within the Cline plugin.

This issue might be related to a potential incompatibility between the plugin and the API format.

### Steps to reproduce

1.Install and configure the Cline plugin in VSCode (version 1.94.2).
2.Set up the plugin with the non-official Claude API key and endpoint.
3.Attempt to send a request through the plugin.
4.Observe the 400 Bad Request error in the output.

### Relevant API REQUEST output

```shell
400 {"timestamp":"2024-12-21T06:03:21.060+00:00","path":"/v1/messages","status":400,"error":"Bad Request","requestId":"da056779-1352482"}
```

### Additional context

![qwertyuo](https://github.com/user-attachments/assets/ff9afa07-3dcc-4807-aa73-11629ce08f38)

**Comment by sergeyprk** [comment]
Try to enter the url without /v1

**Comment by famadeuser** [comment]
> Try to enter the url without /v1

Hi @sergeyprk,

Thanks for the suggestion!

I initially used the plain URL (as shown in the earlier screenshot) and received a 400 Bad Request error.

I also just tried adding /v1 to the URL, but it returned a 404 Not Found error:
```
404 {"timestamp":"2024-12-21T11:21:23.108+00:00","path":"/v1/v1/messages","status":404,"error":"Not Found","requestId":"753b0e99-1382423"}
```
Then I tried /v1/messages, but it resulted in another 404 Not Found error:
```
404 {"timestamp":"2024-12-21T11:23:22.236+00:00","path":"/v1/messages/v1/messages","status":404,"error":"Not Found","requestId":"161d92e7-571535"}
```

While these attempts didn’t resolve the issue, they did give me some ideas to experiment further—so I appreciate your input!

If you have any other suggestions or insights, I’d be happy to try them out.

Thanks again for your help!

**Comment by sergeyprk** [comment]
This error usually occurs when:

- The sent data has an incorrect format.
- Required fields are missing in the request
- The field values do not match the expected format
- Incorrect JSON structure in the request body

To fix it, you need to check:

- Correctness of the format of the data being sent
- Availability of all required fields
- Compliance of field values with API requirements

**Comment by MBrekhof** [comment]
if it works with the official Claude API (which it does) and the anonymous (why?) non-official Claude API does not work it should not be so difficult to determine who is at fault. And that is not Cline.
