### ISSUE TITLE
Auto-approve settings do not work after upgrade to 3.0.x

### ISSUE THREAD

**Issue by cosmix** [cline/cline#978]
### Which API Provider are you using?

Anthropic

### Which Model are you using?

n/a

### What happened?

After upgrading cline to 3.0.0 (and subsequently to 3.0.1 and 3.0.3) the Auto-approve settings do not work at all, which causes cline to constantly ask permission to Read files.

### Steps to reproduce

1. open a workspace in vs.code
2. ask cline to perform a task
3. get requests to 'Read' files in the workspace for every read operation.
4. File bug.

**Comment by Huge** [comment]
Yeah, it seems buggy. In my observation the hierarchy is not visually clear, weird to interact with and what is worse: broken.
If you check the topmost checkbox you do not have to approve anything, but the expected behaviour is that it does the allowed things( ex. read files) and waits before the unchecked( ex. edit files). For me it either did none or all.

**Comment by saoudrizwan** [comment]
@cosmix @Huge very weird! Can I please get a screenshot of your auto approval settings?

**Comment by jmartsch** [comment]
I also have this proplem. Screenshot attached. I upgraded from 2.2 to 3.0 and then went into the settings. One thing I noticed was that after clicking the "Read files and directories" checkbox for the first time, it didn't save. Then I went to settings again and checked it again. Now the checkbox is active, but it always asks for approval.
![image](https://github.com/user-attachments/assets/822a4ce9-caf9-4980-986c-e397c0349a7f)

**Comment by jmartsch** [comment]
Even removing and reinstalling the extension does not solve the problem. Could the problem be that my files are in a WSL2 environment?

**Comment by cosmix** [comment]
No, I’ve had this happen on both Linux and macOS.

**Comment by cosmix** [comment]
I believe this is not a coding issue, but a bad_ui issue. The top-line 'Auto-approve: ...' has a checkbox to the left of it that should be checked for the following auto-approve settings to be enabled. On dark themes, the checkbox 'box' is not visible at all, and is disabled by default.

In addition to making the 'master' checkbox stand out more, if possible, I'd suggest that the checkbox is enabled IF there hasn't been a user-initiated checking/unchecking of the checkbox AND there is at least one 'type' of auto-approval enabled.

@saoudrizwan you can probably close this one.

**Comment by jmartsch** [comment]
@cosmix Indeed, there is a checkbox and when it is checked, the auto approval works. I didn't notice.
![image](https://github.com/user-attachments/assets/09914cd1-d55e-48a7-8103-430f51775fc5)

**Comment by jadbox** [comment]
> the left of it that should be checked for the following auto-approve settings to be enabled. On dark themes, the checkbox 'box' is not visible at all, and is disabled by defa

yep, I was stumped on this too

**Comment by CodeLuca** [comment]
i was stumped too fwiw

**Comment by summit-chris-patrick** [comment]
Confirming I was also confused until finding this issue posted.

**Comment by dsebastien** [comment]
I just started using cline with the Obsidian MCP server (the Python/UVX one). I checked the checkbox to auto approve, as well as the checkboxes for reading, MCP, etc, but auto approve doesn't work. It keeps asking me to approve Obsidian MCP server calls

**Comment by brentarcane** [comment]
The checkbox was invisible for me too, at least with my current IDE theme. Thanks for pointing this out!

**Comment by colinmollenhour** [comment]
Why was this closed? It is still an issue.
I'm thankful that I could Google the question and find this issue with a solution, but surely that is not considered an acceptable UX? I clicked Accept countless times before finally getting frustrated enough to search out the solution and if makes Cline "feel" generally buggy even if this isn't a "bug" per-se.

**Comment by Orest-Cokan** [comment]
Still an issue.

**Comment by cosmoslx** [comment]
I also confirm the issue on version v3.13.3

**Comment by jakenuts** [comment]
The settings don't persist, checking all the "all" options and safe commands checkboxes doesn't seem to persist (on an iPhone so maybe I'm missing a "save" button that commits them). Sort of useless in this state, need autonomy

**Comment by GF-Huang** [comment]
Same issue. `3.17.4`

![Image](https://github.com/user-attachments/assets/cd64e20b-1f11-4bca-a416-41ffe0be341c)

**Comment by MaxmaxmaximusFree** [comment]
so??

**Comment by Orest-Cokan** [comment]
Just use Roo instead lol.

**Comment by MaxmaxmaximusFree** [comment]
> Just use Roo instead lol.

Roo does not allow you to work with one role. And their intercommunication is just a game of dumb telephone, for 20 days that I gave them a chance they NEVER tried to program anything. And the apogee was where I asked to google something, one googled, reported to the other that OK I GOOGLED, and he reported to me - TASK COMPLETED SIR, WE GOOGLED

ahahaha, that was the end of my acquaintance with this "software")

**Comment by aikohanasaki** [comment]
I keep getting asked for permission.

<img width="1026" height="253" alt="Image" src="https://github.com/user-attachments/assets/482461b3-337b-4b2d-b5c9-8ecb9336f998" />

<img width="1061" height="380" alt="Image" src="https://github.com/user-attachments/assets/556e580e-dc5b-462b-99cb-342b89fc463e" />

I click Approve and make sure to check the Auto-approve box.

<img width="1029" height="507" alt="Image" src="https://github.com/user-attachments/assets/a47ae8d0-f8ab-4285-8b7e-21d665699caa" />

It unchecks itself again. 

<img width="1027" height="511" alt="Image" src="https://github.com/user-attachments/assets/5df53a98-1a26-4281-9850-e85125759de5" />
