### ISSUE TITLE
.gitignore interfering with the tool to add folders or files.

### ISSUE THREAD

**Issue by entrepeneur4lyf** [cline/cline#981]
### Which API Provider are you using?

OpenRouter

### Which Model are you using?

Sonnet 3.5 beta

### What happened?

I have noticed (after using cline for many months), that sometime recently, I cannot add any files from folders or files themselves that are listed in .gitignore.

I frequently create a folder named 'devdocs' that I place markdown files in with relevant documentation. It is extremely helpful due to knowedge cutoff by the model.

### Steps to reproduce

1. Add a folder or file to .gitignore
2. Reload the extension or window
3. Try to add the file by instaniating the "add" menu with the @ symbol

### Relevant API REQUEST output

```shell
No output. JUst can't add the file or folder. The menu says "No results found".
```

**Comment by saoudrizwan** [comment]
The extension uses gitignore to determine what files to include in the context mentions menu, particularly any dependencies (i.e. node_modules). The only way for cline to read a file in your gitignore is if you give its path to cline directly (ie right clicking the file and copy path)
